//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.03 at 01:44:53 AM EST 
//


package com.coda.common.schemas.userextension;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * This element holds the list of configuration parameters.
 * 
 * <p>Java class for UserExtensionConfigItemList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UserExtensionConfigItemList"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="UserExtensionConfigItem" type="{http://www.coda.com/common/schemas/userextension}UserExtensionConfigItem" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UserExtensionConfigItemList", propOrder = {
    "userExtensionConfigItem"
})
public class UserExtensionConfigItemList
    implements Serializable
{

    @XmlElement(name = "UserExtensionConfigItem")
    protected List<UserExtensionConfigItem> userExtensionConfigItem;

    /**
     * Gets the value of the userExtensionConfigItem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the userExtensionConfigItem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUserExtensionConfigItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UserExtensionConfigItem }
     * 
     * 
     */
    public List<UserExtensionConfigItem> getUserExtensionConfigItem() {
        if (userExtensionConfigItem == null) {
            userExtensionConfigItem = new ArrayList<UserExtensionConfigItem>();
        }
        return this.userExtensionConfigItem;
    }

}
