//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.03 at 01:43:25 AM EST 
//


package com.coda.efinance.schemas.elementmaster;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Holds details of one of the element's banks.
 * 
 * <p>Java class for BankElement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BankElement"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="DefaultBank" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="Tag" type="{http://www.coda.com/efinance/schemas/common}typeUWord" minOccurs="0"/&gt;
 *         &lt;element name="AccountNumber" type="{http://www.coda.com/efinance/schemas/common}typeBankAccNum"/&gt;
 *         &lt;element name="SortCode" type="{http://www.coda.com/efinance/schemas/common}typeBankSort"/&gt;
 *         &lt;element name="AccountName" type="{http://www.coda.com/efinance/schemas/common}typeBankAccName"/&gt;
 *         &lt;element name="AccountRef" type="{http://www.coda.com/efinance/schemas/common}typeBankAccRef"/&gt;
 *         &lt;element name="BankName" type="{http://www.coda.com/efinance/schemas/common}typeBankName"/&gt;
 *         &lt;element name="Address1" type="{http://www.coda.com/efinance/schemas/common}typeAddress"/&gt;
 *         &lt;element name="Address2" type="{http://www.coda.com/efinance/schemas/common}typeAddress" minOccurs="0"/&gt;
 *         &lt;element name="Address3" type="{http://www.coda.com/efinance/schemas/common}typeAddress" minOccurs="0"/&gt;
 *         &lt;element name="Address4" type="{http://www.coda.com/efinance/schemas/common}typeAddress" minOccurs="0"/&gt;
 *         &lt;element name="Address5" type="{http://www.coda.com/efinance/schemas/common}typeAddress" minOccurs="0"/&gt;
 *         &lt;element name="Address6" type="{http://www.coda.com/efinance/schemas/common}typeAddress" minOccurs="0"/&gt;
 *         &lt;element name="PostCode" type="{http://www.coda.com/efinance/schemas/common}typePostCode" minOccurs="0"/&gt;
 *         &lt;element name="Country" type="{http://www.coda.com/efinance/schemas/common}typeGeneralCodeB" minOccurs="0"/&gt;
 *         &lt;element name="SWIFT" type="{http://www.coda.com/efinance/schemas/common}typeBankSwift" minOccurs="0"/&gt;
 *         &lt;element name="IntBankName" type="{http://www.coda.com/efinance/schemas/common}typeBankName" minOccurs="0"/&gt;
 *         &lt;element name="IntAddress1" type="{http://www.coda.com/efinance/schemas/common}typeAddress" minOccurs="0"/&gt;
 *         &lt;element name="IntAddress2" type="{http://www.coda.com/efinance/schemas/common}typeAddress" minOccurs="0"/&gt;
 *         &lt;element name="IntAddress3" type="{http://www.coda.com/efinance/schemas/common}typeAddress" minOccurs="0"/&gt;
 *         &lt;element name="IntAddress4" type="{http://www.coda.com/efinance/schemas/common}typeAddress" minOccurs="0"/&gt;
 *         &lt;element name="IntAddress5" type="{http://www.coda.com/efinance/schemas/common}typeAddress" minOccurs="0"/&gt;
 *         &lt;element name="IntAddress6" type="{http://www.coda.com/efinance/schemas/common}typeAddress" minOccurs="0"/&gt;
 *         &lt;element name="IntPostCode" type="{http://www.coda.com/efinance/schemas/common}typeAddress" minOccurs="0"/&gt;
 *         &lt;element name="IntCountry" type="{http://www.coda.com/efinance/schemas/common}typeGeneralCodeB" minOccurs="0"/&gt;
 *         &lt;element name="IBAN" type="{http://www.coda.com/efinance/schemas/common}typeIBANB" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BankElement", propOrder = {
    "defaultBank",
    "tag",
    "accountNumber",
    "sortCode",
    "accountName",
    "accountRef",
    "bankName",
    "address1",
    "address2",
    "address3",
    "address4",
    "address5",
    "address6",
    "postCode",
    "country",
    "swift",
    "intBankName",
    "intAddress1",
    "intAddress2",
    "intAddress3",
    "intAddress4",
    "intAddress5",
    "intAddress6",
    "intPostCode",
    "intCountry",
    "iban"
})
public class BankElement
    implements Serializable
{

    @XmlElement(name = "DefaultBank")
    protected boolean defaultBank;
    @XmlElement(name = "Tag")
    protected Short tag;
    @XmlElement(name = "AccountNumber", required = true)
    protected String accountNumber;
    @XmlElement(name = "SortCode", required = true)
    protected String sortCode;
    @XmlElement(name = "AccountName", required = true)
    protected String accountName;
    @XmlElement(name = "AccountRef", required = true)
    protected String accountRef;
    @XmlElement(name = "BankName", required = true)
    protected String bankName;
    @XmlElement(name = "Address1", required = true)
    protected String address1;
    @XmlElement(name = "Address2")
    protected String address2;
    @XmlElement(name = "Address3")
    protected String address3;
    @XmlElement(name = "Address4")
    protected String address4;
    @XmlElement(name = "Address5")
    protected String address5;
    @XmlElement(name = "Address6")
    protected String address6;
    @XmlElement(name = "PostCode")
    protected String postCode;
    @XmlElement(name = "Country")
    protected String country;
    @XmlElement(name = "SWIFT")
    protected String swift;
    @XmlElement(name = "IntBankName")
    protected String intBankName;
    @XmlElement(name = "IntAddress1")
    protected String intAddress1;
    @XmlElement(name = "IntAddress2")
    protected String intAddress2;
    @XmlElement(name = "IntAddress3")
    protected String intAddress3;
    @XmlElement(name = "IntAddress4")
    protected String intAddress4;
    @XmlElement(name = "IntAddress5")
    protected String intAddress5;
    @XmlElement(name = "IntAddress6")
    protected String intAddress6;
    @XmlElement(name = "IntPostCode")
    protected String intPostCode;
    @XmlElement(name = "IntCountry")
    protected String intCountry;
    @XmlElement(name = "IBAN")
    protected String iban;

    /**
     * Gets the value of the defaultBank property.
     * 
     */
    public boolean isDefaultBank() {
        return defaultBank;
    }

    /**
     * Sets the value of the defaultBank property.
     * 
     */
    public void setDefaultBank(boolean value) {
        this.defaultBank = value;
    }

    /**
     * Gets the value of the tag property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getTag() {
        return tag;
    }

    /**
     * Sets the value of the tag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setTag(Short value) {
        this.tag = value;
    }

    /**
     * Gets the value of the accountNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountNumber() {
        return accountNumber;
    }

    /**
     * Sets the value of the accountNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountNumber(String value) {
        this.accountNumber = value;
    }

    /**
     * Gets the value of the sortCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSortCode() {
        return sortCode;
    }

    /**
     * Sets the value of the sortCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSortCode(String value) {
        this.sortCode = value;
    }

    /**
     * Gets the value of the accountName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * Sets the value of the accountName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountName(String value) {
        this.accountName = value;
    }

    /**
     * Gets the value of the accountRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountRef() {
        return accountRef;
    }

    /**
     * Sets the value of the accountRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountRef(String value) {
        this.accountRef = value;
    }

    /**
     * Gets the value of the bankName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * Sets the value of the bankName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBankName(String value) {
        this.bankName = value;
    }

    /**
     * Gets the value of the address1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddress1() {
        return address1;
    }

    /**
     * Sets the value of the address1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddress1(String value) {
        this.address1 = value;
    }

    /**
     * Gets the value of the address2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddress2() {
        return address2;
    }

    /**
     * Sets the value of the address2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddress2(String value) {
        this.address2 = value;
    }

    /**
     * Gets the value of the address3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddress3() {
        return address3;
    }

    /**
     * Sets the value of the address3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddress3(String value) {
        this.address3 = value;
    }

    /**
     * Gets the value of the address4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddress4() {
        return address4;
    }

    /**
     * Sets the value of the address4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddress4(String value) {
        this.address4 = value;
    }

    /**
     * Gets the value of the address5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddress5() {
        return address5;
    }

    /**
     * Sets the value of the address5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddress5(String value) {
        this.address5 = value;
    }

    /**
     * Gets the value of the address6 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddress6() {
        return address6;
    }

    /**
     * Sets the value of the address6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddress6(String value) {
        this.address6 = value;
    }

    /**
     * Gets the value of the postCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostCode() {
        return postCode;
    }

    /**
     * Sets the value of the postCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostCode(String value) {
        this.postCode = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountry(String value) {
        this.country = value;
    }

    /**
     * Gets the value of the swift property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSWIFT() {
        return swift;
    }

    /**
     * Sets the value of the swift property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSWIFT(String value) {
        this.swift = value;
    }

    /**
     * Gets the value of the intBankName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntBankName() {
        return intBankName;
    }

    /**
     * Sets the value of the intBankName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntBankName(String value) {
        this.intBankName = value;
    }

    /**
     * Gets the value of the intAddress1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntAddress1() {
        return intAddress1;
    }

    /**
     * Sets the value of the intAddress1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntAddress1(String value) {
        this.intAddress1 = value;
    }

    /**
     * Gets the value of the intAddress2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntAddress2() {
        return intAddress2;
    }

    /**
     * Sets the value of the intAddress2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntAddress2(String value) {
        this.intAddress2 = value;
    }

    /**
     * Gets the value of the intAddress3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntAddress3() {
        return intAddress3;
    }

    /**
     * Sets the value of the intAddress3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntAddress3(String value) {
        this.intAddress3 = value;
    }

    /**
     * Gets the value of the intAddress4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntAddress4() {
        return intAddress4;
    }

    /**
     * Sets the value of the intAddress4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntAddress4(String value) {
        this.intAddress4 = value;
    }

    /**
     * Gets the value of the intAddress5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntAddress5() {
        return intAddress5;
    }

    /**
     * Sets the value of the intAddress5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntAddress5(String value) {
        this.intAddress5 = value;
    }

    /**
     * Gets the value of the intAddress6 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntAddress6() {
        return intAddress6;
    }

    /**
     * Sets the value of the intAddress6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntAddress6(String value) {
        this.intAddress6 = value;
    }

    /**
     * Gets the value of the intPostCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntPostCode() {
        return intPostCode;
    }

    /**
     * Sets the value of the intPostCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntPostCode(String value) {
        this.intPostCode = value;
    }

    /**
     * Gets the value of the intCountry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntCountry() {
        return intCountry;
    }

    /**
     * Sets the value of the intCountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntCountry(String value) {
        this.intCountry = value;
    }

    /**
     * Gets the value of the iban property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIBAN() {
        return iban;
    }

    /**
     * Sets the value of the iban property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIBAN(String value) {
        this.iban = value;
    }

}
