//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.03 at 01:43:25 AM EST 
//


package com.coda.efinance.schemas.elementmaster;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * This element holds an element master.
 * 
 * <p>Java class for Element complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Element"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.coda.com/efinance/schemas/elementmaster}Master"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Addresses" type="{http://www.coda.com/efinance/schemas/elementmaster}AddressData" minOccurs="0"/&gt;
 *         &lt;element name="Banks" type="{http://www.coda.com/efinance/schemas/elementmaster}BankData" minOccurs="0"/&gt;
 *         &lt;element name="Comments" type="{http://www.coda.com/efinance/schemas/elementmaster}CommentData" minOccurs="0"/&gt;
 *         &lt;element name="Groups" type="{http://www.coda.com/efinance/schemas/elementmaster}GroupData" minOccurs="0"/&gt;
 *         &lt;element name="Medias" type="{http://www.coda.com/efinance/schemas/elementmaster}MediaData" minOccurs="0"/&gt;
 *         &lt;element name="LeftRules" type="{http://www.coda.com/efinance/schemas/elementmaster}RuleData" minOccurs="0"/&gt;
 *         &lt;element name="RightRules" type="{http://www.coda.com/efinance/schemas/elementmaster}RuleData" minOccurs="0"/&gt;
 *         &lt;element name="Mnemonics" type="{http://www.coda.com/efinance/schemas/elementmaster}MnemonicData" minOccurs="0"/&gt;
 *         &lt;element name="PunchoutAdvancedParams" type="{http://www.coda.com/efinance/schemas/elementmaster}PunchoutData" minOccurs="0"/&gt;
 *         &lt;element name="OutputDevices" type="{http://www.coda.com/efinance/schemas/elementmaster}OutputDeviceData" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Element", propOrder = {
    "addresses",
    "banks",
    "comments",
    "groups",
    "medias",
    "leftRules",
    "rightRules",
    "mnemonics",
    "punchoutAdvancedParams",
    "outputDevices"
})
public class Element
    extends Master
    implements Serializable
{

    @XmlElement(name = "Addresses")
    protected AddressData addresses;
    @XmlElement(name = "Banks")
    protected BankData banks;
    @XmlElement(name = "Comments")
    protected CommentData comments;
    @XmlElement(name = "Groups")
    protected GroupData groups;
    @XmlElement(name = "Medias")
    protected MediaData medias;
    @XmlElement(name = "LeftRules")
    protected RuleData leftRules;
    @XmlElement(name = "RightRules")
    protected RuleData rightRules;
    @XmlElement(name = "Mnemonics")
    protected MnemonicData mnemonics;
    @XmlElement(name = "PunchoutAdvancedParams")
    protected PunchoutData punchoutAdvancedParams;
    @XmlElement(name = "OutputDevices")
    protected OutputDeviceData outputDevices;

    /**
     * Gets the value of the addresses property.
     * 
     * @return
     *     possible object is
     *     {@link AddressData }
     *     
     */
    public AddressData getAddresses() {
        return addresses;
    }

    /**
     * Sets the value of the addresses property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressData }
     *     
     */
    public void setAddresses(AddressData value) {
        this.addresses = value;
    }

    /**
     * Gets the value of the banks property.
     * 
     * @return
     *     possible object is
     *     {@link BankData }
     *     
     */
    public BankData getBanks() {
        return banks;
    }

    /**
     * Sets the value of the banks property.
     * 
     * @param value
     *     allowed object is
     *     {@link BankData }
     *     
     */
    public void setBanks(BankData value) {
        this.banks = value;
    }

    /**
     * Gets the value of the comments property.
     * 
     * @return
     *     possible object is
     *     {@link CommentData }
     *     
     */
    public CommentData getComments() {
        return comments;
    }

    /**
     * Sets the value of the comments property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommentData }
     *     
     */
    public void setComments(CommentData value) {
        this.comments = value;
    }

    /**
     * Gets the value of the groups property.
     * 
     * @return
     *     possible object is
     *     {@link GroupData }
     *     
     */
    public GroupData getGroups() {
        return groups;
    }

    /**
     * Sets the value of the groups property.
     * 
     * @param value
     *     allowed object is
     *     {@link GroupData }
     *     
     */
    public void setGroups(GroupData value) {
        this.groups = value;
    }

    /**
     * Gets the value of the medias property.
     * 
     * @return
     *     possible object is
     *     {@link MediaData }
     *     
     */
    public MediaData getMedias() {
        return medias;
    }

    /**
     * Sets the value of the medias property.
     * 
     * @param value
     *     allowed object is
     *     {@link MediaData }
     *     
     */
    public void setMedias(MediaData value) {
        this.medias = value;
    }

    /**
     * Gets the value of the leftRules property.
     * 
     * @return
     *     possible object is
     *     {@link RuleData }
     *     
     */
    public RuleData getLeftRules() {
        return leftRules;
    }

    /**
     * Sets the value of the leftRules property.
     * 
     * @param value
     *     allowed object is
     *     {@link RuleData }
     *     
     */
    public void setLeftRules(RuleData value) {
        this.leftRules = value;
    }

    /**
     * Gets the value of the rightRules property.
     * 
     * @return
     *     possible object is
     *     {@link RuleData }
     *     
     */
    public RuleData getRightRules() {
        return rightRules;
    }

    /**
     * Sets the value of the rightRules property.
     * 
     * @param value
     *     allowed object is
     *     {@link RuleData }
     *     
     */
    public void setRightRules(RuleData value) {
        this.rightRules = value;
    }

    /**
     * Gets the value of the mnemonics property.
     * 
     * @return
     *     possible object is
     *     {@link MnemonicData }
     *     
     */
    public MnemonicData getMnemonics() {
        return mnemonics;
    }

    /**
     * Sets the value of the mnemonics property.
     * 
     * @param value
     *     allowed object is
     *     {@link MnemonicData }
     *     
     */
    public void setMnemonics(MnemonicData value) {
        this.mnemonics = value;
    }

    /**
     * Gets the value of the punchoutAdvancedParams property.
     * 
     * @return
     *     possible object is
     *     {@link PunchoutData }
     *     
     */
    public PunchoutData getPunchoutAdvancedParams() {
        return punchoutAdvancedParams;
    }

    /**
     * Sets the value of the punchoutAdvancedParams property.
     * 
     * @param value
     *     allowed object is
     *     {@link PunchoutData }
     *     
     */
    public void setPunchoutAdvancedParams(PunchoutData value) {
        this.punchoutAdvancedParams = value;
    }

    /**
     * Gets the value of the outputDevices property.
     * 
     * @return
     *     possible object is
     *     {@link OutputDeviceData }
     *     
     */
    public OutputDeviceData getOutputDevices() {
        return outputDevices;
    }

    /**
     * Sets the value of the outputDevices property.
     * 
     * @param value
     *     allowed object is
     *     {@link OutputDeviceData }
     *     
     */
    public void setOutputDevices(OutputDeviceData value) {
        this.outputDevices = value;
    }

}
