//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.03 at 01:44:53 AM EST 
//


package com.coda.common.schemas.usermaster;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * This element contains details of a mapping between this user and a domain user.
 * 
 * <p>Java class for DomainUserMapping complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DomainUserMapping"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="DomainUser" type="{http://www.coda.com/efinance/schemas/common}typeDomainUser"/&gt;
 *         &lt;element name="SecondaryPasswordRequired" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="DefaultMapping" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DomainUserMapping", propOrder = {
    "domainUser",
    "secondaryPasswordRequired",
    "defaultMapping"
})
public class DomainUserMapping
    implements Serializable
{

    @XmlElement(name = "DomainUser", required = true)
    protected String domainUser;
    @XmlElement(name = "SecondaryPasswordRequired", defaultValue = "false")
    protected boolean secondaryPasswordRequired;
    @XmlElement(name = "DefaultMapping", defaultValue = "false")
    protected boolean defaultMapping;

    /**
     * Gets the value of the domainUser property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDomainUser() {
        return domainUser;
    }

    /**
     * Sets the value of the domainUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDomainUser(String value) {
        this.domainUser = value;
    }

    /**
     * Gets the value of the secondaryPasswordRequired property.
     * 
     */
    public boolean isSecondaryPasswordRequired() {
        return secondaryPasswordRequired;
    }

    /**
     * Sets the value of the secondaryPasswordRequired property.
     * 
     */
    public void setSecondaryPasswordRequired(boolean value) {
        this.secondaryPasswordRequired = value;
    }

    /**
     * Gets the value of the defaultMapping property.
     * 
     */
    public boolean isDefaultMapping() {
        return defaultMapping;
    }

    /**
     * Sets the value of the defaultMapping property.
     * 
     */
    public void setDefaultMapping(boolean value) {
        this.defaultMapping = value;
    }

}
