//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.03 at 01:44:46 AM EST 
//


package com.coda.common.schemas.usermaster;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.coda.efinance.schemas.common.Response;


/**
 * <p>Java class for ExportResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExportResponse"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.coda.com/efinance/schemas/common}Response"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="FullUserList" type="{http://www.coda.com/common/schemas/usermaster}FullUserList" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExportResponse", propOrder = {
    "fullUserList"
})
public class ExportResponse
    extends Response
    implements Serializable
{

    @XmlElement(name = "FullUserList")
    protected FullUserList fullUserList;

    /**
     * Gets the value of the fullUserList property.
     * 
     * @return
     *     possible object is
     *     {@link FullUserList }
     *     
     */
    public FullUserList getFullUserList() {
        return fullUserList;
    }

    /**
     * Sets the value of the fullUserList property.
     * 
     * @param value
     *     allowed object is
     *     {@link FullUserList }
     *     
     */
    public void setFullUserList(FullUserList value) {
        this.fullUserList = value;
    }

}
