//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.03 at 01:44:53 AM EST 
//


package com.coda.common.schemas.usermaster;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * This element contains the user master settings for Finance.
 * 
 * <p>Java class for Finance complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Finance"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="DefaultCompany" type="{http://www.coda.com/efinance/schemas/common}typeGeneralCode" minOccurs="0"/&gt;
 *         &lt;element name="OpenDocumentLimit" type="{http://www.w3.org/2001/XMLSchema}short" minOccurs="0"/&gt;
 *         &lt;element name="DefaultElementLevel" type="{http://www.coda.com/common/schemas/usermaster}UserMasterElmLevel" minOccurs="0"/&gt;
 *         &lt;element name="DefaultElementCode" type="{http://www.coda.com/efinance/schemas/common}typeElmCodeB" minOccurs="0"/&gt;
 *         &lt;element name="DefaultElementLevel2" type="{http://www.coda.com/common/schemas/usermaster}UserMasterElmLevel" minOccurs="0"/&gt;
 *         &lt;element name="DefaultElementCode2" type="{http://www.coda.com/efinance/schemas/common}typeElmCodeB" minOccurs="0"/&gt;
 *         &lt;element name="DefaultElementLevel3" type="{http://www.coda.com/common/schemas/usermaster}UserMasterElmLevel" minOccurs="0"/&gt;
 *         &lt;element name="DefaultElementCode3" type="{http://www.coda.com/efinance/schemas/common}typeElmCodeB" minOccurs="0"/&gt;
 *         &lt;element name="CompanyList" type="{http://www.coda.com/common/schemas/usermaster}CompanyList" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Finance", propOrder = {
    "defaultCompany",
    "openDocumentLimit",
    "defaultElementLevel",
    "defaultElementCode",
    "defaultElementLevel2",
    "defaultElementCode2",
    "defaultElementLevel3",
    "defaultElementCode3",
    "companyList"
})
public class Finance
    implements Serializable
{

    @XmlElement(name = "DefaultCompany")
    protected String defaultCompany;
    @XmlElement(name = "OpenDocumentLimit")
    protected Short openDocumentLimit;
    @XmlElement(name = "DefaultElementLevel")
    protected Short defaultElementLevel;
    @XmlElement(name = "DefaultElementCode")
    protected String defaultElementCode;
    @XmlElement(name = "DefaultElementLevel2")
    protected Short defaultElementLevel2;
    @XmlElement(name = "DefaultElementCode2")
    protected String defaultElementCode2;
    @XmlElement(name = "DefaultElementLevel3")
    protected Short defaultElementLevel3;
    @XmlElement(name = "DefaultElementCode3")
    protected String defaultElementCode3;
    @XmlElement(name = "CompanyList")
    protected CompanyList companyList;

    /**
     * Gets the value of the defaultCompany property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultCompany() {
        return defaultCompany;
    }

    /**
     * Sets the value of the defaultCompany property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultCompany(String value) {
        this.defaultCompany = value;
    }

    /**
     * Gets the value of the openDocumentLimit property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getOpenDocumentLimit() {
        return openDocumentLimit;
    }

    /**
     * Sets the value of the openDocumentLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setOpenDocumentLimit(Short value) {
        this.openDocumentLimit = value;
    }

    /**
     * Gets the value of the defaultElementLevel property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getDefaultElementLevel() {
        return defaultElementLevel;
    }

    /**
     * Sets the value of the defaultElementLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setDefaultElementLevel(Short value) {
        this.defaultElementLevel = value;
    }

    /**
     * Gets the value of the defaultElementCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultElementCode() {
        return defaultElementCode;
    }

    /**
     * Sets the value of the defaultElementCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultElementCode(String value) {
        this.defaultElementCode = value;
    }

    /**
     * Gets the value of the defaultElementLevel2 property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getDefaultElementLevel2() {
        return defaultElementLevel2;
    }

    /**
     * Sets the value of the defaultElementLevel2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setDefaultElementLevel2(Short value) {
        this.defaultElementLevel2 = value;
    }

    /**
     * Gets the value of the defaultElementCode2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultElementCode2() {
        return defaultElementCode2;
    }

    /**
     * Sets the value of the defaultElementCode2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultElementCode2(String value) {
        this.defaultElementCode2 = value;
    }

    /**
     * Gets the value of the defaultElementLevel3 property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getDefaultElementLevel3() {
        return defaultElementLevel3;
    }

    /**
     * Sets the value of the defaultElementLevel3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setDefaultElementLevel3(Short value) {
        this.defaultElementLevel3 = value;
    }

    /**
     * Gets the value of the defaultElementCode3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultElementCode3() {
        return defaultElementCode3;
    }

    /**
     * Sets the value of the defaultElementCode3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultElementCode3(String value) {
        this.defaultElementCode3 = value;
    }

    /**
     * Gets the value of the companyList property.
     * 
     * @return
     *     possible object is
     *     {@link CompanyList }
     *     
     */
    public CompanyList getCompanyList() {
        return companyList;
    }

    /**
     * Sets the value of the companyList property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompanyList }
     *     
     */
    public void setCompanyList(CompanyList value) {
        this.companyList = value;
    }

}
