//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.03 at 01:44:53 AM EST 
//


package com.coda.common.schemas.usermaster;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.coda.common.schemas.usermaster package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.coda.common.schemas.usermaster
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link OutOfOffice }
     * 
     */
    public OutOfOffice createOutOfOffice() {
        return new OutOfOffice();
    }

    /**
     * Create an instance of {@link BrowseWorkListSetting }
     * 
     */
    public BrowseWorkListSetting createBrowseWorkListSetting() {
        return new BrowseWorkListSetting();
    }

    /**
     * Create an instance of {@link BrowseWorkListSettingList }
     * 
     */
    public BrowseWorkListSettingList createBrowseWorkListSettingList() {
        return new BrowseWorkListSettingList();
    }

    /**
     * Create an instance of {@link ElementResponsibilities }
     * 
     */
    public ElementResponsibilities createElementResponsibilities() {
        return new ElementResponsibilities();
    }

    /**
     * Create an instance of {@link ResponsibilityList }
     * 
     */
    public ResponsibilityList createResponsibilityList() {
        return new ResponsibilityList();
    }

    /**
     * Create an instance of {@link Responsibility }
     * 
     */
    public Responsibility createResponsibility() {
        return new Responsibility();
    }

    /**
     * Create an instance of {@link ElementResponsibility }
     * 
     */
    public ElementResponsibility createElementResponsibility() {
        return new ElementResponsibility();
    }

    /**
     * Create an instance of {@link ElementResponsibilityList }
     * 
     */
    public ElementResponsibilityList createElementResponsibilityList() {
        return new ElementResponsibilityList();
    }

    /**
     * Create an instance of {@link MyPreferences }
     * 
     */
    public MyPreferences createMyPreferences() {
        return new MyPreferences();
    }

    /**
     * Create an instance of {@link DomainUserMappingList }
     * 
     */
    public DomainUserMappingList createDomainUserMappingList() {
        return new DomainUserMappingList();
    }

    /**
     * Create an instance of {@link DomainUserMapping }
     * 
     */
    public DomainUserMapping createDomainUserMapping() {
        return new DomainUserMapping();
    }

    /**
     * Create an instance of {@link UserRoleList }
     * 
     */
    public UserRoleList createUserRoleList() {
        return new UserRoleList();
    }

    /**
     * Create an instance of {@link UserRole }
     * 
     */
    public UserRole createUserRole() {
        return new UserRole();
    }

    /**
     * Create an instance of {@link NTUserLogon }
     * 
     */
    public NTUserLogon createNTUserLogon() {
        return new NTUserLogon();
    }

    /**
     * Create an instance of {@link Property }
     * 
     */
    public Property createProperty() {
        return new Property();
    }

    /**
     * Create an instance of {@link PropertyList }
     * 
     */
    public PropertyList createPropertyList() {
        return new PropertyList();
    }

    /**
     * Create an instance of {@link CompanyItem }
     * 
     */
    public CompanyItem createCompanyItem() {
        return new CompanyItem();
    }

    /**
     * Create an instance of {@link CompanyList }
     * 
     */
    public CompanyList createCompanyList() {
        return new CompanyList();
    }

    /**
     * Create an instance of {@link Finance }
     * 
     */
    public Finance createFinance() {
        return new Finance();
    }

    /**
     * Create an instance of {@link UserApplications }
     * 
     */
    public UserApplications createUserApplications() {
        return new UserApplications();
    }

    /**
     * Create an instance of {@link UserApplication }
     * 
     */
    public UserApplication createUserApplication() {
        return new UserApplication();
    }

    /**
     * Create an instance of {@link AuthenticateArgs }
     * 
     */
    public AuthenticateArgs createAuthenticateArgs() {
        return new AuthenticateArgs();
    }

    /**
     * Create an instance of {@link AuthenticateArg }
     * 
     */
    public AuthenticateArg createAuthenticateArg() {
        return new AuthenticateArg();
    }

    /**
     * Create an instance of {@link HomePage }
     * 
     */
    public HomePage createHomePage() {
        return new HomePage();
    }

    /**
     * Create an instance of {@link Procurement }
     * 
     */
    public Procurement createProcurement() {
        return new Procurement();
    }

    /**
     * Create an instance of {@link ProcurementCompanies }
     * 
     */
    public ProcurementCompanies createProcurementCompanies() {
        return new ProcurementCompanies();
    }

    /**
     * Create an instance of {@link ProcurementCompany }
     * 
     */
    public ProcurementCompany createProcurementCompany() {
        return new ProcurementCompany();
    }

    /**
     * Create an instance of {@link UserKey }
     * 
     */
    public UserKey createUserKey() {
        return new UserKey();
    }

    /**
     * Create an instance of {@link UserList }
     * 
     */
    public UserList createUserList() {
        return new UserList();
    }

    /**
     * Create an instance of {@link UserListItem }
     * 
     */
    public UserListItem createUserListItem() {
        return new UserListItem();
    }

    /**
     * Create an instance of {@link FullUserList }
     * 
     */
    public FullUserList createFullUserList() {
        return new FullUserList();
    }

    /**
     * Create an instance of {@link Groups }
     * 
     */
    public Groups createGroups() {
        return new Groups();
    }

    /**
     * Create an instance of {@link Positions }
     * 
     */
    public Positions createPositions() {
        return new Positions();
    }

    /**
     * Create an instance of {@link Hierarchies }
     * 
     */
    public Hierarchies createHierarchies() {
        return new Hierarchies();
    }

    /**
     * Create an instance of {@link ListFilter }
     * 
     */
    public ListFilter createListFilter() {
        return new ListFilter();
    }

}
