//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.03 at 01:44:53 AM EST 
//


package com.coda.common.schemas.usermaster;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * This element contains out of office details.
 * 
 * <p>Java class for OutOfOffice complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OutOfOffice"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="OutOfOfficeStatus" type="{http://www.coda.com/efinance/schemas/common}typeBaseEnum" minOccurs="0"/&gt;
 *         &lt;element name="OutOfOfficeFrom" type="{http://www.coda.com/efinance/schemas/common}typeDate" minOccurs="0"/&gt;
 *         &lt;element name="OutOfOfficeTo" type="{http://www.coda.com/efinance/schemas/common}typeDate" minOccurs="0"/&gt;
 *         &lt;element name="StoreAlerts" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="DelegateTo" type="{http://www.coda.com/efinance/schemas/common}typeUserCode" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OutOfOffice", propOrder = {
    "outOfOfficeStatus",
    "outOfOfficeFrom",
    "outOfOfficeTo",
    "storeAlerts",
    "delegateTo"
})
public class OutOfOffice
    implements Serializable
{

    @XmlElement(name = "OutOfOfficeStatus")
    protected String outOfOfficeStatus;
    @XmlElement(name = "OutOfOfficeFrom")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar outOfOfficeFrom;
    @XmlElement(name = "OutOfOfficeTo")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar outOfOfficeTo;
    @XmlElement(name = "StoreAlerts")
    protected Boolean storeAlerts;
    @XmlElement(name = "DelegateTo")
    protected String delegateTo;

    /**
     * Gets the value of the outOfOfficeStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutOfOfficeStatus() {
        return outOfOfficeStatus;
    }

    /**
     * Sets the value of the outOfOfficeStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutOfOfficeStatus(String value) {
        this.outOfOfficeStatus = value;
    }

    /**
     * Gets the value of the outOfOfficeFrom property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getOutOfOfficeFrom() {
        return outOfOfficeFrom;
    }

    /**
     * Sets the value of the outOfOfficeFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setOutOfOfficeFrom(XMLGregorianCalendar value) {
        this.outOfOfficeFrom = value;
    }

    /**
     * Gets the value of the outOfOfficeTo property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getOutOfOfficeTo() {
        return outOfOfficeTo;
    }

    /**
     * Sets the value of the outOfOfficeTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setOutOfOfficeTo(XMLGregorianCalendar value) {
        this.outOfOfficeTo = value;
    }

    /**
     * Gets the value of the storeAlerts property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isStoreAlerts() {
        return storeAlerts;
    }

    /**
     * Sets the value of the storeAlerts property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setStoreAlerts(Boolean value) {
        this.storeAlerts = value;
    }

    /**
     * Gets the value of the delegateTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDelegateTo() {
        return delegateTo;
    }

    /**
     * Sets the value of the delegateTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDelegateTo(String value) {
        this.delegateTo = value;
    }

}
