//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.03 at 01:44:46 AM EST 
//


package com.coda.common.schemas.usermaster;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UpdateWithPositionsResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UpdateWithPositionsResponse"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.coda.com/common/schemas/usermaster}UpdateResponse"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Success" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="ExternallyAddedPositions" type="{http://www.coda.com/common/schemas/usermaster}Positions" minOccurs="0"/&gt;
 *         &lt;element name="ExternallyRemovedPositions" type="{http://www.coda.com/common/schemas/usermaster}Positions" minOccurs="0"/&gt;
 *         &lt;element name="ExternallyDeletedPositions" type="{http://www.coda.com/common/schemas/usermaster}Positions" minOccurs="0"/&gt;
 *         &lt;element name="SelectedPositions" type="{http://www.coda.com/common/schemas/usermaster}Positions" minOccurs="0"/&gt;
 *         &lt;element name="SelectedHierarchies" type="{http://www.coda.com/common/schemas/usermaster}Hierarchies" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UpdateWithPositionsResponse", propOrder = {
    "success",
    "externallyAddedPositions",
    "externallyRemovedPositions",
    "externallyDeletedPositions",
    "selectedPositions",
    "selectedHierarchies"
})
public class UpdateWithPositionsResponse
    extends UpdateResponse
    implements Serializable
{

    @XmlElement(name = "Success")
    protected boolean success;
    @XmlElement(name = "ExternallyAddedPositions")
    protected Positions externallyAddedPositions;
    @XmlElement(name = "ExternallyRemovedPositions")
    protected Positions externallyRemovedPositions;
    @XmlElement(name = "ExternallyDeletedPositions")
    protected Positions externallyDeletedPositions;
    @XmlElement(name = "SelectedPositions")
    protected Positions selectedPositions;
    @XmlElement(name = "SelectedHierarchies")
    protected Hierarchies selectedHierarchies;

    /**
     * Gets the value of the success property.
     * 
     */
    public boolean isSuccess() {
        return success;
    }

    /**
     * Sets the value of the success property.
     * 
     */
    public void setSuccess(boolean value) {
        this.success = value;
    }

    /**
     * Gets the value of the externallyAddedPositions property.
     * 
     * @return
     *     possible object is
     *     {@link Positions }
     *     
     */
    public Positions getExternallyAddedPositions() {
        return externallyAddedPositions;
    }

    /**
     * Sets the value of the externallyAddedPositions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Positions }
     *     
     */
    public void setExternallyAddedPositions(Positions value) {
        this.externallyAddedPositions = value;
    }

    /**
     * Gets the value of the externallyRemovedPositions property.
     * 
     * @return
     *     possible object is
     *     {@link Positions }
     *     
     */
    public Positions getExternallyRemovedPositions() {
        return externallyRemovedPositions;
    }

    /**
     * Sets the value of the externallyRemovedPositions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Positions }
     *     
     */
    public void setExternallyRemovedPositions(Positions value) {
        this.externallyRemovedPositions = value;
    }

    /**
     * Gets the value of the externallyDeletedPositions property.
     * 
     * @return
     *     possible object is
     *     {@link Positions }
     *     
     */
    public Positions getExternallyDeletedPositions() {
        return externallyDeletedPositions;
    }

    /**
     * Sets the value of the externallyDeletedPositions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Positions }
     *     
     */
    public void setExternallyDeletedPositions(Positions value) {
        this.externallyDeletedPositions = value;
    }

    /**
     * Gets the value of the selectedPositions property.
     * 
     * @return
     *     possible object is
     *     {@link Positions }
     *     
     */
    public Positions getSelectedPositions() {
        return selectedPositions;
    }

    /**
     * Sets the value of the selectedPositions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Positions }
     *     
     */
    public void setSelectedPositions(Positions value) {
        this.selectedPositions = value;
    }

    /**
     * Gets the value of the selectedHierarchies property.
     * 
     * @return
     *     possible object is
     *     {@link Hierarchies }
     *     
     */
    public Hierarchies getSelectedHierarchies() {
        return selectedHierarchies;
    }

    /**
     * Sets the value of the selectedHierarchies property.
     * 
     * @param value
     *     allowed object is
     *     {@link Hierarchies }
     *     
     */
    public void setSelectedHierarchies(Hierarchies value) {
        this.selectedHierarchies = value;
    }

}
