//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.03 at 01:43:50 AM EST 
//


package com.coda.efinance.schemas.matching;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.coda.efinance.schemas.common.Request;
import com.coda.efinance.schemas.progress.ProgressKey;


/**
 * <p>Java class for GetGroupLinesRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetGroupLinesRequest"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.coda.com/efinance/schemas/common}Request"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ProgressKey" type="{http://www.coda.com/efinance/schemas/progress}ProgressKey"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetGroupLinesRequest", propOrder = {
    "progressKey"
})
public class GetGroupLinesRequest
    extends Request
    implements Serializable
{

    @XmlElement(name = "ProgressKey", required = true)
    protected ProgressKey progressKey;

    /**
     * Gets the value of the progressKey property.
     * 
     * @return
     *     possible object is
     *     {@link ProgressKey }
     *     
     */
    public ProgressKey getProgressKey() {
        return progressKey;
    }

    /**
     * Sets the value of the progressKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProgressKey }
     *     
     */
    public void setProgressKey(ProgressKey value) {
        this.progressKey = value;
    }

}
