//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.03 at 01:43:50 AM EST 
//


package com.coda.efinance.schemas.matching;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import com.coda.efinance.schemas.association.AsoKey;
import com.coda.efinance.schemas.common.TypeCtMatchCommitType;


/**
 * This element contains details of a matching group in the matching session.
 * 
 * <p>Java class for MatchGroup complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MatchGroup"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="GroupNum" type="{http://www.w3.org/2001/XMLSchema}short"/&gt;
 *         &lt;element name="UserRefs" type="{http://www.coda.com/efinance/schemas/matching}UserRefs" minOccurs="0"/&gt;
 *         &lt;element name="CommitType" type="{http://www.coda.com/efinance/schemas/common}typeCtMatchCommitType" minOccurs="0"/&gt;
 *         &lt;element name="IgnoreWarnings" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="DrivingLine" type="{http://www.coda.com/efinance/schemas/association}asoKey" minOccurs="0"/&gt;
 *         &lt;element name="InputDrivingLine" type="{http://www.coda.com/efinance/schemas/association}asoKey" minOccurs="0"/&gt;
 *         &lt;element name="PayDetailsSource" type="{http://www.coda.com/efinance/schemas/association}asoKey" minOccurs="0"/&gt;
 *         &lt;element name="Lines" type="{http://www.coda.com/efinance/schemas/matching}MatchLines"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MatchGroup", propOrder = {
    "groupNum",
    "userRefs",
    "commitType",
    "ignoreWarnings",
    "drivingLine",
    "inputDrivingLine",
    "payDetailsSource",
    "lines"
})
public class MatchGroup
    implements Serializable
{

    @XmlElement(name = "GroupNum")
    protected short groupNum;
    @XmlElement(name = "UserRefs")
    protected UserRefs userRefs;
    @XmlElement(name = "CommitType")
    @XmlSchemaType(name = "string")
    protected TypeCtMatchCommitType commitType;
    @XmlElement(name = "IgnoreWarnings")
    protected Boolean ignoreWarnings;
    @XmlElement(name = "DrivingLine")
    protected AsoKey drivingLine;
    @XmlElement(name = "InputDrivingLine")
    protected AsoKey inputDrivingLine;
    @XmlElement(name = "PayDetailsSource")
    protected AsoKey payDetailsSource;
    @XmlElement(name = "Lines", required = true)
    protected MatchLines lines;

    /**
     * Gets the value of the groupNum property.
     * 
     */
    public short getGroupNum() {
        return groupNum;
    }

    /**
     * Sets the value of the groupNum property.
     * 
     */
    public void setGroupNum(short value) {
        this.groupNum = value;
    }

    /**
     * Gets the value of the userRefs property.
     * 
     * @return
     *     possible object is
     *     {@link UserRefs }
     *     
     */
    public UserRefs getUserRefs() {
        return userRefs;
    }

    /**
     * Sets the value of the userRefs property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserRefs }
     *     
     */
    public void setUserRefs(UserRefs value) {
        this.userRefs = value;
    }

    /**
     * Gets the value of the commitType property.
     * 
     * @return
     *     possible object is
     *     {@link TypeCtMatchCommitType }
     *     
     */
    public TypeCtMatchCommitType getCommitType() {
        return commitType;
    }

    /**
     * Sets the value of the commitType property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeCtMatchCommitType }
     *     
     */
    public void setCommitType(TypeCtMatchCommitType value) {
        this.commitType = value;
    }

    /**
     * Gets the value of the ignoreWarnings property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIgnoreWarnings() {
        return ignoreWarnings;
    }

    /**
     * Sets the value of the ignoreWarnings property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIgnoreWarnings(Boolean value) {
        this.ignoreWarnings = value;
    }

    /**
     * Gets the value of the drivingLine property.
     * 
     * @return
     *     possible object is
     *     {@link AsoKey }
     *     
     */
    public AsoKey getDrivingLine() {
        return drivingLine;
    }

    /**
     * Sets the value of the drivingLine property.
     * 
     * @param value
     *     allowed object is
     *     {@link AsoKey }
     *     
     */
    public void setDrivingLine(AsoKey value) {
        this.drivingLine = value;
    }

    /**
     * Gets the value of the inputDrivingLine property.
     * 
     * @return
     *     possible object is
     *     {@link AsoKey }
     *     
     */
    public AsoKey getInputDrivingLine() {
        return inputDrivingLine;
    }

    /**
     * Sets the value of the inputDrivingLine property.
     * 
     * @param value
     *     allowed object is
     *     {@link AsoKey }
     *     
     */
    public void setInputDrivingLine(AsoKey value) {
        this.inputDrivingLine = value;
    }

    /**
     * Gets the value of the payDetailsSource property.
     * 
     * @return
     *     possible object is
     *     {@link AsoKey }
     *     
     */
    public AsoKey getPayDetailsSource() {
        return payDetailsSource;
    }

    /**
     * Sets the value of the payDetailsSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link AsoKey }
     *     
     */
    public void setPayDetailsSource(AsoKey value) {
        this.payDetailsSource = value;
    }

    /**
     * Gets the value of the lines property.
     * 
     * @return
     *     possible object is
     *     {@link MatchLines }
     *     
     */
    public MatchLines getLines() {
        return lines;
    }

    /**
     * Sets the value of the lines property.
     * 
     * @param value
     *     allowed object is
     *     {@link MatchLines }
     *     
     */
    public void setLines(MatchLines value) {
        this.lines = value;
    }

}
