//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.03 at 01:43:50 AM EST 
//


package com.coda.efinance.schemas.matching;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.coda.efinance.schemas.association.AssistantScript;
import com.coda.efinance.schemas.common.Request;


/**
 * <p>Java class for StartBackgroundRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StartBackgroundRequest"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.coda.com/efinance/schemas/common}Request"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="MatchingParams" type="{http://www.coda.com/efinance/schemas/matching}MatchingParams"/&gt;
 *         &lt;element name="Folders" type="{http://www.coda.com/efinance/schemas/matching}SelectFolders"/&gt;
 *         &lt;element name="Assistant" type="{http://www.coda.com/efinance/schemas/association}AssistantScript"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StartBackgroundRequest", propOrder = {
    "matchingParams",
    "folders",
    "assistant"
})
public class StartBackgroundRequest
    extends Request
    implements Serializable
{

    @XmlElement(name = "MatchingParams", required = true)
    protected MatchingParams matchingParams;
    @XmlElement(name = "Folders", required = true)
    protected SelectFolders folders;
    @XmlElement(name = "Assistant", required = true)
    protected AssistantScript assistant;

    /**
     * Gets the value of the matchingParams property.
     * 
     * @return
     *     possible object is
     *     {@link MatchingParams }
     *     
     */
    public MatchingParams getMatchingParams() {
        return matchingParams;
    }

    /**
     * Sets the value of the matchingParams property.
     * 
     * @param value
     *     allowed object is
     *     {@link MatchingParams }
     *     
     */
    public void setMatchingParams(MatchingParams value) {
        this.matchingParams = value;
    }

    /**
     * Gets the value of the folders property.
     * 
     * @return
     *     possible object is
     *     {@link SelectFolders }
     *     
     */
    public SelectFolders getFolders() {
        return folders;
    }

    /**
     * Sets the value of the folders property.
     * 
     * @param value
     *     allowed object is
     *     {@link SelectFolders }
     *     
     */
    public void setFolders(SelectFolders value) {
        this.folders = value;
    }

    /**
     * Gets the value of the assistant property.
     * 
     * @return
     *     possible object is
     *     {@link AssistantScript }
     *     
     */
    public AssistantScript getAssistant() {
        return assistant;
    }

    /**
     * Sets the value of the assistant property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssistantScript }
     *     
     */
    public void setAssistant(AssistantScript value) {
        this.assistant = value;
    }

}
