//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.03 at 01:43:50 AM EST 
//


package com.coda.efinance.schemas.matching;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * This element contains user references that will be copied to all document lines in the current matching group.
 * 
 * <p>Java class for UserRefs complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UserRefs"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="UserRef1" type="{http://www.coda.com/efinance/schemas/common}typeUserRefB" minOccurs="0"/&gt;
 *         &lt;element name="UserRef2" type="{http://www.coda.com/efinance/schemas/common}typeUserRefB" minOccurs="0"/&gt;
 *         &lt;element name="UserRef3" type="{http://www.coda.com/efinance/schemas/common}typeUserRefB" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UserRefs", propOrder = {
    "userRef1",
    "userRef2",
    "userRef3"
})
public class UserRefs
    implements Serializable
{

    @XmlElement(name = "UserRef1")
    protected String userRef1;
    @XmlElement(name = "UserRef2")
    protected String userRef2;
    @XmlElement(name = "UserRef3")
    protected String userRef3;

    /**
     * Gets the value of the userRef1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserRef1() {
        return userRef1;
    }

    /**
     * Sets the value of the userRef1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserRef1(String value) {
        this.userRef1 = value;
    }

    /**
     * Gets the value of the userRef2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserRef2() {
        return userRef2;
    }

    /**
     * Sets the value of the userRef2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserRef2(String value) {
        this.userRef2 = value;
    }

    /**
     * Gets the value of the userRef3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserRef3() {
        return userRef3;
    }

    /**
     * Sets the value of the userRef3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserRef3(String value) {
        this.userRef3 = value;
    }

}
