//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.03 at 01:44:38 AM EST 
//


package com.coda.common.schemas.positions;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.coda.common.schemas.udfmaster.UDFDefinedValueKey;


/**
 * This element contains details of an attribute.
 * 
 * <p>Java class for PositionAttribute complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PositionAttribute"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Definition" type="{http://www.coda.com/common/schemas/positions}PositionAttributeDefinitionKey"/&gt;
 *         &lt;element name="Value" type="{http://www.coda.com/efinance/schemas/common}typeUdfTextb" minOccurs="0"/&gt;
 *         &lt;element name="DefinedValue" type="{http://www.coda.com/common/schemas/udfmaster}UDFDefinedValueKey" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PositionAttribute", propOrder = {
    "definition",
    "value",
    "definedValue"
})
public class PositionAttribute
    implements Serializable
{

    @XmlElement(name = "Definition", required = true)
    protected PositionAttributeDefinitionKey definition;
    @XmlElement(name = "Value")
    protected String value;
    @XmlElement(name = "DefinedValue")
    protected UDFDefinedValueKey definedValue;

    /**
     * Gets the value of the definition property.
     * 
     * @return
     *     possible object is
     *     {@link PositionAttributeDefinitionKey }
     *     
     */
    public PositionAttributeDefinitionKey getDefinition() {
        return definition;
    }

    /**
     * Sets the value of the definition property.
     * 
     * @param value
     *     allowed object is
     *     {@link PositionAttributeDefinitionKey }
     *     
     */
    public void setDefinition(PositionAttributeDefinitionKey value) {
        this.definition = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the definedValue property.
     * 
     * @return
     *     possible object is
     *     {@link UDFDefinedValueKey }
     *     
     */
    public UDFDefinedValueKey getDefinedValue() {
        return definedValue;
    }

    /**
     * Sets the value of the definedValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link UDFDefinedValueKey }
     *     
     */
    public void setDefinedValue(UDFDefinedValueKey value) {
        this.definedValue = value;
    }

}
