//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.03 at 01:43:50 AM EST 
//


package com.coda.efinance.schemas.matchingmaster;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Folder complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Folder"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="SelCode" type="{http://www.coda.com/efinance/schemas/common}typeGeneralCode" minOccurs="0"/&gt;
 *         &lt;element name="NumLines" type="{http://www.w3.org/2001/XMLSchema}short"/&gt;
 *         &lt;element name="Title" type="{http://www.coda.com/efinance/schemas/common}typeTitle" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Folder", propOrder = {
    "selCode",
    "numLines",
    "title"
})
@XmlSeeAlso({
    Folder1 .class,
    Folder2 .class
})
public abstract class Folder
    implements Serializable
{

    @XmlElement(name = "SelCode")
    protected String selCode;
    @XmlElement(name = "NumLines")
    protected short numLines;
    @XmlElement(name = "Title")
    protected String title;

    /**
     * Gets the value of the selCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSelCode() {
        return selCode;
    }

    /**
     * Sets the value of the selCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSelCode(String value) {
        this.selCode = value;
    }

    /**
     * Gets the value of the numLines property.
     * 
     */
    public short getNumLines() {
        return numLines;
    }

    /**
     * Sets the value of the numLines property.
     * 
     */
    public void setNumLines(short value) {
        this.numLines = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

}
