//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.03 at 01:43:50 AM EST 
//


package com.coda.efinance.schemas.matchingmaster;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * This element contains parameters to determine which document lines are displayed in Folder 2.
 * 
 * <p>Java class for Folder2 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Folder2"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.coda.com/efinance/schemas/matchingmaster}Folder"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="PresCode" type="{http://www.coda.com/efinance/schemas/common}typeGeneralCode" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Folder2", propOrder = {
    "presCode"
})
public class Folder2
    extends Folder
    implements Serializable
{

    @XmlElement(name = "PresCode")
    protected String presCode;

    /**
     * Gets the value of the presCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPresCode() {
        return presCode;
    }

    /**
     * Sets the value of the presCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPresCode(String value) {
        this.presCode = value;
    }

}
