//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.03 at 01:43:50 AM EST 
//


package com.coda.efinance.schemas.matchingmaster;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * This element contains parameters that are used when a match results in postings.
 * 
 * <p>Java class for PostingParams complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PostingParams"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="MatchingDate" type="{http://www.coda.com/efinance/schemas/common}typeHSDate" minOccurs="0"/&gt;
 *         &lt;element name="Period" type="{http://www.coda.com/efinance/schemas/common}typePeriodAny" minOccurs="0"/&gt;
 *         &lt;element name="DiscAcc" type="{http://www.coda.com/efinance/schemas/common}typeAcCodeWild" minOccurs="0"/&gt;
 *         &lt;element name="WOffAcc" type="{http://www.coda.com/efinance/schemas/common}typeAcCodeWild" minOccurs="0"/&gt;
 *         &lt;element name="CurrWOffAcc" type="{http://www.coda.com/efinance/schemas/common}typeAcCodeWild" minOccurs="0"/&gt;
 *         &lt;element name="RestrictAcc" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PostingParams", propOrder = {
    "matchingDate",
    "period",
    "discAcc",
    "wOffAcc",
    "currWOffAcc",
    "restrictAcc"
})
public class PostingParams
    implements Serializable
{

    @XmlElement(name = "MatchingDate")
    protected String matchingDate;
    @XmlElement(name = "Period")
    protected String period;
    @XmlElement(name = "DiscAcc")
    protected String discAcc;
    @XmlElement(name = "WOffAcc")
    protected String wOffAcc;
    @XmlElement(name = "CurrWOffAcc")
    protected String currWOffAcc;
    @XmlElement(name = "RestrictAcc")
    protected boolean restrictAcc;

    /**
     * Gets the value of the matchingDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMatchingDate() {
        return matchingDate;
    }

    /**
     * Sets the value of the matchingDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMatchingDate(String value) {
        this.matchingDate = value;
    }

    /**
     * Gets the value of the period property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPeriod() {
        return period;
    }

    /**
     * Sets the value of the period property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPeriod(String value) {
        this.period = value;
    }

    /**
     * Gets the value of the discAcc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiscAcc() {
        return discAcc;
    }

    /**
     * Sets the value of the discAcc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiscAcc(String value) {
        this.discAcc = value;
    }

    /**
     * Gets the value of the wOffAcc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWOffAcc() {
        return wOffAcc;
    }

    /**
     * Sets the value of the wOffAcc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWOffAcc(String value) {
        this.wOffAcc = value;
    }

    /**
     * Gets the value of the currWOffAcc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrWOffAcc() {
        return currWOffAcc;
    }

    /**
     * Sets the value of the currWOffAcc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrWOffAcc(String value) {
        this.currWOffAcc = value;
    }

    /**
     * Gets the value of the restrictAcc property.
     * 
     */
    public boolean isRestrictAcc() {
        return restrictAcc;
    }

    /**
     * Sets the value of the restrictAcc property.
     * 
     */
    public void setRestrictAcc(boolean value) {
        this.restrictAcc = value;
    }

}
