//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.03 at 01:43:37 AM EST 
//


package com.coda.efinance.schemas.documentmaster;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.coda.efinance.schemas.documentmaster package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DocumentMaster_QNAME = new QName("http://www.coda.com/efinance/schemas/documentmaster", "DocumentMaster");
    private final static QName _DocumentMasterRequest_QNAME = new QName("http://www.coda.com/efinance/schemas/documentmaster", "DocumentMasterRequest");
    private final static QName _DocumentMasterResponse_QNAME = new QName("http://www.coda.com/efinance/schemas/documentmaster", "DocumentMasterResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.coda.efinance.schemas.documentmaster
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DocumentMaster }
     * 
     */
    public DocumentMaster createDocumentMaster() {
        return new DocumentMaster();
    }

    /**
     * Create an instance of {@link DocumentMasterRequest }
     * 
     */
    public DocumentMasterRequest createDocumentMasterRequest() {
        return new DocumentMasterRequest();
    }

    /**
     * Create an instance of {@link DocumentMasterResponse }
     * 
     */
    public DocumentMasterResponse createDocumentMasterResponse() {
        return new DocumentMasterResponse();
    }

    /**
     * Create an instance of {@link Recurring }
     * 
     */
    public Recurring createRecurring() {
        return new Recurring();
    }

    /**
     * Create an instance of {@link FieldAccess }
     * 
     */
    public FieldAccess createFieldAccess() {
        return new FieldAccess();
    }

    /**
     * Create an instance of {@link PreDefinedLines }
     * 
     */
    public PreDefinedLines createPreDefinedLines() {
        return new PreDefinedLines();
    }

    /**
     * Create an instance of {@link UserReference }
     * 
     */
    public UserReference createUserReference() {
        return new UserReference();
    }

    /**
     * Create an instance of {@link UserReferences }
     * 
     */
    public UserReferences createUserReferences() {
        return new UserReferences();
    }

    /**
     * Create an instance of {@link Intercompany }
     * 
     */
    public Intercompany createIntercompany() {
        return new Intercompany();
    }

    /**
     * Create an instance of {@link ExtRefCompare }
     * 
     */
    public ExtRefCompare createExtRefCompare() {
        return new ExtRefCompare();
    }

    /**
     * Create an instance of {@link ExtRefChecking }
     * 
     */
    public ExtRefChecking createExtRefChecking() {
        return new ExtRefChecking();
    }

    /**
     * Create an instance of {@link ExtRef }
     * 
     */
    public ExtRef createExtRef() {
        return new ExtRef();
    }

    /**
     * Create an instance of {@link ExtRefCombined }
     * 
     */
    public ExtRefCombined createExtRefCombined() {
        return new ExtRefCombined();
    }

    /**
     * Create an instance of {@link ExternalReferences }
     * 
     */
    public ExternalReferences createExternalReferences() {
        return new ExternalReferences();
    }

    /**
     * Create an instance of {@link AnalysisLines }
     * 
     */
    public AnalysisLines createAnalysisLines() {
        return new AnalysisLines();
    }

    /**
     * Create an instance of {@link SummaryLines }
     * 
     */
    public SummaryLines createSummaryLines() {
        return new SummaryLines();
    }

    /**
     * Create an instance of {@link Quantities }
     * 
     */
    public Quantities createQuantities() {
        return new Quantities();
    }

    /**
     * Create an instance of {@link PayElement }
     * 
     */
    public PayElement createPayElement() {
        return new PayElement();
    }

    /**
     * Create an instance of {@link PayData }
     * 
     */
    public PayData createPayData() {
        return new PayData();
    }

    /**
     * Create an instance of {@link Pay }
     * 
     */
    public Pay createPay() {
        return new Pay();
    }

    /**
     * Create an instance of {@link BalancingElements }
     * 
     */
    public BalancingElements createBalancingElements() {
        return new BalancingElements();
    }

    /**
     * Create an instance of {@link DocTax }
     * 
     */
    public DocTax createDocTax() {
        return new DocTax();
    }

    /**
     * Create an instance of {@link Currency }
     * 
     */
    public Currency createCurrency() {
        return new Currency();
    }

    /**
     * Create an instance of {@link ValueDate }
     * 
     */
    public ValueDate createValueDate() {
        return new ValueDate();
    }

    /**
     * Create an instance of {@link DueDate }
     * 
     */
    public DueDate createDueDate() {
        return new DueDate();
    }

    /**
     * Create an instance of {@link DocSelectKey }
     * 
     */
    public DocSelectKey createDocSelectKey() {
        return new DocSelectKey();
    }

    /**
     * Create an instance of {@link DocReserveKey }
     * 
     */
    public DocReserveKey createDocReserveKey() {
        return new DocReserveKey();
    }

    /**
     * Create an instance of {@link PrintDocSelectKey }
     * 
     */
    public PrintDocSelectKey createPrintDocSelectKey() {
        return new PrintDocSelectKey();
    }

    /**
     * Create an instance of {@link ProtectedElements }
     * 
     */
    public ProtectedElements createProtectedElements() {
        return new ProtectedElements();
    }

    /**
     * Create an instance of {@link PDLExtRefs }
     * 
     */
    public PDLExtRefs createPDLExtRefs() {
        return new PDLExtRefs();
    }

    /**
     * Create an instance of {@link PDL }
     * 
     */
    public PDL createPDL() {
        return new PDL();
    }

    /**
     * Create an instance of {@link PDLList }
     * 
     */
    public PDLList createPDLList() {
        return new PDLList();
    }

    /**
     * Create an instance of {@link DocNumListItem }
     * 
     */
    public DocNumListItem createDocNumListItem() {
        return new DocNumListItem();
    }

    /**
     * Create an instance of {@link DocNumList }
     * 
     */
    public DocNumList createDocNumList() {
        return new DocNumList();
    }

    /**
     * Create an instance of {@link Master }
     * 
     */
    public Master createMaster() {
        return new Master();
    }

    /**
     * Create an instance of {@link GetRequest }
     * 
     */
    public GetRequest createGetRequest() {
        return new GetRequest();
    }

    /**
     * Create an instance of {@link GetRequestVerb }
     * 
     */
    public GetRequestVerb createGetRequestVerb() {
        return new GetRequestVerb();
    }

    /**
     * Create an instance of {@link GetResponse }
     * 
     */
    public GetResponse createGetResponse() {
        return new GetResponse();
    }

    /**
     * Create an instance of {@link GetResponseVerb }
     * 
     */
    public GetResponseVerb createGetResponseVerb() {
        return new GetResponseVerb();
    }

    /**
     * Create an instance of {@link AddRequest }
     * 
     */
    public AddRequest createAddRequest() {
        return new AddRequest();
    }

    /**
     * Create an instance of {@link AddRequestVerb }
     * 
     */
    public AddRequestVerb createAddRequestVerb() {
        return new AddRequestVerb();
    }

    /**
     * Create an instance of {@link AddResponse }
     * 
     */
    public AddResponse createAddResponse() {
        return new AddResponse();
    }

    /**
     * Create an instance of {@link AddResponseVerb }
     * 
     */
    public AddResponseVerb createAddResponseVerb() {
        return new AddResponseVerb();
    }

    /**
     * Create an instance of {@link UpdateRequest }
     * 
     */
    public UpdateRequest createUpdateRequest() {
        return new UpdateRequest();
    }

    /**
     * Create an instance of {@link UpdateRequestVerb }
     * 
     */
    public UpdateRequestVerb createUpdateRequestVerb() {
        return new UpdateRequestVerb();
    }

    /**
     * Create an instance of {@link UpdateResponse }
     * 
     */
    public UpdateResponse createUpdateResponse() {
        return new UpdateResponse();
    }

    /**
     * Create an instance of {@link UpdateResponseVerb }
     * 
     */
    public UpdateResponseVerb createUpdateResponseVerb() {
        return new UpdateResponseVerb();
    }

    /**
     * Create an instance of {@link DeleteRequest }
     * 
     */
    public DeleteRequest createDeleteRequest() {
        return new DeleteRequest();
    }

    /**
     * Create an instance of {@link DeleteRequestVerb }
     * 
     */
    public DeleteRequestVerb createDeleteRequestVerb() {
        return new DeleteRequestVerb();
    }

    /**
     * Create an instance of {@link DeleteResponse }
     * 
     */
    public DeleteResponse createDeleteResponse() {
        return new DeleteResponse();
    }

    /**
     * Create an instance of {@link DeleteResponseVerb }
     * 
     */
    public DeleteResponseVerb createDeleteResponseVerb() {
        return new DeleteResponseVerb();
    }

    /**
     * Create an instance of {@link GetNoListsRequest }
     * 
     */
    public GetNoListsRequest createGetNoListsRequest() {
        return new GetNoListsRequest();
    }

    /**
     * Create an instance of {@link GetNoListsRequestVerb }
     * 
     */
    public GetNoListsRequestVerb createGetNoListsRequestVerb() {
        return new GetNoListsRequestVerb();
    }

    /**
     * Create an instance of {@link GetNoListsResponse }
     * 
     */
    public GetNoListsResponse createGetNoListsResponse() {
        return new GetNoListsResponse();
    }

    /**
     * Create an instance of {@link GetNoListsResponseVerb }
     * 
     */
    public GetNoListsResponseVerb createGetNoListsResponseVerb() {
        return new GetNoListsResponseVerb();
    }

    /**
     * Create an instance of {@link ListRequest }
     * 
     */
    public ListRequest createListRequest() {
        return new ListRequest();
    }

    /**
     * Create an instance of {@link ListRequestVerb }
     * 
     */
    public ListRequestVerb createListRequestVerb() {
        return new ListRequestVerb();
    }

    /**
     * Create an instance of {@link ListResponse }
     * 
     */
    public ListResponse createListResponse() {
        return new ListResponse();
    }

    /**
     * Create an instance of {@link ListResponseVerb }
     * 
     */
    public ListResponseVerb createListResponseVerb() {
        return new ListResponseVerb();
    }

    /**
     * Create an instance of {@link ReserveRequest }
     * 
     */
    public ReserveRequest createReserveRequest() {
        return new ReserveRequest();
    }

    /**
     * Create an instance of {@link ReserveRequestVerb }
     * 
     */
    public ReserveRequestVerb createReserveRequestVerb() {
        return new ReserveRequestVerb();
    }

    /**
     * Create an instance of {@link ReserveResponse }
     * 
     */
    public ReserveResponse createReserveResponse() {
        return new ReserveResponse();
    }

    /**
     * Create an instance of {@link ReserveResponseVerb }
     * 
     */
    public ReserveResponseVerb createReserveResponseVerb() {
        return new ReserveResponseVerb();
    }

    /**
     * Create an instance of {@link ReleaseReservationRequest }
     * 
     */
    public ReleaseReservationRequest createReleaseReservationRequest() {
        return new ReleaseReservationRequest();
    }

    /**
     * Create an instance of {@link ReleaseReservationRequestVerb }
     * 
     */
    public ReleaseReservationRequestVerb createReleaseReservationRequestVerb() {
        return new ReleaseReservationRequestVerb();
    }

    /**
     * Create an instance of {@link ReleaseReservationResponse }
     * 
     */
    public ReleaseReservationResponse createReleaseReservationResponse() {
        return new ReleaseReservationResponse();
    }

    /**
     * Create an instance of {@link ReleaseReservationResponseVerb }
     * 
     */
    public ReleaseReservationResponseVerb createReleaseReservationResponseVerb() {
        return new ReleaseReservationResponseVerb();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DocumentMaster }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.coda.com/efinance/schemas/documentmaster", name = "DocumentMaster")
    public JAXBElement<DocumentMaster> createDocumentMaster(DocumentMaster value) {
        return new JAXBElement<DocumentMaster>(_DocumentMaster_QNAME, DocumentMaster.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DocumentMasterRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.coda.com/efinance/schemas/documentmaster", name = "DocumentMasterRequest")
    public JAXBElement<DocumentMasterRequest> createDocumentMasterRequest(DocumentMasterRequest value) {
        return new JAXBElement<DocumentMasterRequest>(_DocumentMasterRequest_QNAME, DocumentMasterRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DocumentMasterResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.coda.com/efinance/schemas/documentmaster", name = "DocumentMasterResponse")
    public JAXBElement<DocumentMasterResponse> createDocumentMasterResponse(DocumentMasterResponse value) {
        return new JAXBElement<DocumentMasterResponse>(_DocumentMasterResponse_QNAME, DocumentMasterResponse.class, null, value);
    }

}
