//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.03 at 01:43:12 AM EST 
//


package com.coda.efinance.schemas.currency;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.coda.efinance.schemas.currency package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Currency_QNAME = new QName("http://www.coda.com/efinance/schemas/currency", "Currency");
    private final static QName _CurrencyRate_QNAME = new QName("http://www.coda.com/efinance/schemas/currency", "CurrencyRate");
    private final static QName _CurrencyRequest_QNAME = new QName("http://www.coda.com/efinance/schemas/currency", "CurrencyRequest");
    private final static QName _CurrencyResponse_QNAME = new QName("http://www.coda.com/efinance/schemas/currency", "CurrencyResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.coda.efinance.schemas.currency
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Currency }
     * 
     */
    public Currency createCurrency() {
        return new Currency();
    }

    /**
     * Create an instance of {@link CurrencyRate }
     * 
     */
    public CurrencyRate createCurrencyRate() {
        return new CurrencyRate();
    }

    /**
     * Create an instance of {@link CurrencyRequest }
     * 
     */
    public CurrencyRequest createCurrencyRequest() {
        return new CurrencyRequest();
    }

    /**
     * Create an instance of {@link CurrencyResponse }
     * 
     */
    public CurrencyResponse createCurrencyResponse() {
        return new CurrencyResponse();
    }

    /**
     * Create an instance of {@link RateDataElement }
     * 
     */
    public RateDataElement createRateDataElement() {
        return new RateDataElement();
    }

    /**
     * Create an instance of {@link RateData }
     * 
     */
    public RateData createRateData() {
        return new RateData();
    }

    /**
     * Create an instance of {@link InfCaseElements }
     * 
     */
    public InfCaseElements createInfCaseElements() {
        return new InfCaseElements();
    }

    /**
     * Create an instance of {@link InfCaseElementsData }
     * 
     */
    public InfCaseElementsData createInfCaseElementsData() {
        return new InfCaseElementsData();
    }

    /**
     * Create an instance of {@link InfDataElement }
     * 
     */
    public InfDataElement createInfDataElement() {
        return new InfDataElement();
    }

    /**
     * Create an instance of {@link InfData }
     * 
     */
    public InfData createInfData() {
        return new InfData();
    }

    /**
     * Create an instance of {@link CurrencyRateKey }
     * 
     */
    public CurrencyRateKey createCurrencyRateKey() {
        return new CurrencyRateKey();
    }

    /**
     * Create an instance of {@link CurrencyRateDataElement }
     * 
     */
    public CurrencyRateDataElement createCurrencyRateDataElement() {
        return new CurrencyRateDataElement();
    }

    /**
     * Create an instance of {@link CurrencyRateData }
     * 
     */
    public CurrencyRateData createCurrencyRateData() {
        return new CurrencyRateData();
    }

    /**
     * Create an instance of {@link ExchangeRateDataElement }
     * 
     */
    public ExchangeRateDataElement createExchangeRateDataElement() {
        return new ExchangeRateDataElement();
    }

    /**
     * Create an instance of {@link ExchangeRateData }
     * 
     */
    public ExchangeRateData createExchangeRateData() {
        return new ExchangeRateData();
    }

    /**
     * Create an instance of {@link CurrExchangeRate }
     * 
     */
    public CurrExchangeRate createCurrExchangeRate() {
        return new CurrExchangeRate();
    }

    /**
     * Create an instance of {@link CurrencyExchangeRate }
     * 
     */
    public CurrencyExchangeRate createCurrencyExchangeRate() {
        return new CurrencyExchangeRate();
    }

    /**
     * Create an instance of {@link CurrencyListFilter }
     * 
     */
    public CurrencyListFilter createCurrencyListFilter() {
        return new CurrencyListFilter();
    }

    /**
     * Create an instance of {@link AddRequest }
     * 
     */
    public AddRequest createAddRequest() {
        return new AddRequest();
    }

    /**
     * Create an instance of {@link AddRequestVerb }
     * 
     */
    public AddRequestVerb createAddRequestVerb() {
        return new AddRequestVerb();
    }

    /**
     * Create an instance of {@link AddResponse }
     * 
     */
    public AddResponse createAddResponse() {
        return new AddResponse();
    }

    /**
     * Create an instance of {@link AddResponseVerb }
     * 
     */
    public AddResponseVerb createAddResponseVerb() {
        return new AddResponseVerb();
    }

    /**
     * Create an instance of {@link UpdateRequest }
     * 
     */
    public UpdateRequest createUpdateRequest() {
        return new UpdateRequest();
    }

    /**
     * Create an instance of {@link UpdateRequestVerb }
     * 
     */
    public UpdateRequestVerb createUpdateRequestVerb() {
        return new UpdateRequestVerb();
    }

    /**
     * Create an instance of {@link UpdateResponse }
     * 
     */
    public UpdateResponse createUpdateResponse() {
        return new UpdateResponse();
    }

    /**
     * Create an instance of {@link UpdateResponseVerb }
     * 
     */
    public UpdateResponseVerb createUpdateResponseVerb() {
        return new UpdateResponseVerb();
    }

    /**
     * Create an instance of {@link GetRequest }
     * 
     */
    public GetRequest createGetRequest() {
        return new GetRequest();
    }

    /**
     * Create an instance of {@link GetRequestVerb }
     * 
     */
    public GetRequestVerb createGetRequestVerb() {
        return new GetRequestVerb();
    }

    /**
     * Create an instance of {@link GetResponse }
     * 
     */
    public GetResponse createGetResponse() {
        return new GetResponse();
    }

    /**
     * Create an instance of {@link GetResponseVerb }
     * 
     */
    public GetResponseVerb createGetResponseVerb() {
        return new GetResponseVerb();
    }

    /**
     * Create an instance of {@link DeleteRequest }
     * 
     */
    public DeleteRequest createDeleteRequest() {
        return new DeleteRequest();
    }

    /**
     * Create an instance of {@link DeleteRequestVerb }
     * 
     */
    public DeleteRequestVerb createDeleteRequestVerb() {
        return new DeleteRequestVerb();
    }

    /**
     * Create an instance of {@link DeleteResponse }
     * 
     */
    public DeleteResponse createDeleteResponse() {
        return new DeleteResponse();
    }

    /**
     * Create an instance of {@link DeleteResponseVerb }
     * 
     */
    public DeleteResponseVerb createDeleteResponseVerb() {
        return new DeleteResponseVerb();
    }

    /**
     * Create an instance of {@link ListRequest }
     * 
     */
    public ListRequest createListRequest() {
        return new ListRequest();
    }

    /**
     * Create an instance of {@link ListRequestVerb }
     * 
     */
    public ListRequestVerb createListRequestVerb() {
        return new ListRequestVerb();
    }

    /**
     * Create an instance of {@link ListResponse }
     * 
     */
    public ListResponse createListResponse() {
        return new ListResponse();
    }

    /**
     * Create an instance of {@link ListResponseVerb }
     * 
     */
    public ListResponseVerb createListResponseVerb() {
        return new ListResponseVerb();
    }

    /**
     * Create an instance of {@link ListAllRequest }
     * 
     */
    public ListAllRequest createListAllRequest() {
        return new ListAllRequest();
    }

    /**
     * Create an instance of {@link ListAllRequestVerb }
     * 
     */
    public ListAllRequestVerb createListAllRequestVerb() {
        return new ListAllRequestVerb();
    }

    /**
     * Create an instance of {@link ListAllResponse }
     * 
     */
    public ListAllResponse createListAllResponse() {
        return new ListAllResponse();
    }

    /**
     * Create an instance of {@link ListAllResponseVerb }
     * 
     */
    public ListAllResponseVerb createListAllResponseVerb() {
        return new ListAllResponseVerb();
    }

    /**
     * Create an instance of {@link GetRateRequest }
     * 
     */
    public GetRateRequest createGetRateRequest() {
        return new GetRateRequest();
    }

    /**
     * Create an instance of {@link GetRateRequestVerb }
     * 
     */
    public GetRateRequestVerb createGetRateRequestVerb() {
        return new GetRateRequestVerb();
    }

    /**
     * Create an instance of {@link GetRateResponse }
     * 
     */
    public GetRateResponse createGetRateResponse() {
        return new GetRateResponse();
    }

    /**
     * Create an instance of {@link GetRateResponseVerb }
     * 
     */
    public GetRateResponseVerb createGetRateResponseVerb() {
        return new GetRateResponseVerb();
    }

    /**
     * Create an instance of {@link AddRateRequest }
     * 
     */
    public AddRateRequest createAddRateRequest() {
        return new AddRateRequest();
    }

    /**
     * Create an instance of {@link AddRateRequestVerb }
     * 
     */
    public AddRateRequestVerb createAddRateRequestVerb() {
        return new AddRateRequestVerb();
    }

    /**
     * Create an instance of {@link AddRateResponse }
     * 
     */
    public AddRateResponse createAddRateResponse() {
        return new AddRateResponse();
    }

    /**
     * Create an instance of {@link AddRateResponseVerb }
     * 
     */
    public AddRateResponseVerb createAddRateResponseVerb() {
        return new AddRateResponseVerb();
    }

    /**
     * Create an instance of {@link UpdateRateRequest }
     * 
     */
    public UpdateRateRequest createUpdateRateRequest() {
        return new UpdateRateRequest();
    }

    /**
     * Create an instance of {@link UpdateRateRequestVerb }
     * 
     */
    public UpdateRateRequestVerb createUpdateRateRequestVerb() {
        return new UpdateRateRequestVerb();
    }

    /**
     * Create an instance of {@link UpdateRateResponse }
     * 
     */
    public UpdateRateResponse createUpdateRateResponse() {
        return new UpdateRateResponse();
    }

    /**
     * Create an instance of {@link UpdateRateResponseVerb }
     * 
     */
    public UpdateRateResponseVerb createUpdateRateResponseVerb() {
        return new UpdateRateResponseVerb();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Currency }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.coda.com/efinance/schemas/currency", name = "Currency")
    public JAXBElement<Currency> createCurrency(Currency value) {
        return new JAXBElement<Currency>(_Currency_QNAME, Currency.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CurrencyRate }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.coda.com/efinance/schemas/currency", name = "CurrencyRate")
    public JAXBElement<CurrencyRate> createCurrencyRate(CurrencyRate value) {
        return new JAXBElement<CurrencyRate>(_CurrencyRate_QNAME, CurrencyRate.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CurrencyRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.coda.com/efinance/schemas/currency", name = "CurrencyRequest")
    public JAXBElement<CurrencyRequest> createCurrencyRequest(CurrencyRequest value) {
        return new JAXBElement<CurrencyRequest>(_CurrencyRequest_QNAME, CurrencyRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CurrencyResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.coda.com/efinance/schemas/currency", name = "CurrencyResponse")
    public JAXBElement<CurrencyResponse> createCurrencyResponse(CurrencyResponse value) {
        return new JAXBElement<CurrencyResponse>(_CurrencyResponse_QNAME, CurrencyResponse.class, null, value);
    }

}
