//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.03 at 01:43:12 AM EST 
//


package com.coda.efinance.schemas.currency;

import java.io.Serializable;
import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import com.coda.efinance.schemas.common.TypeCtCurParentType;
import com.coda.efinance.schemas.common.TypeCtMulDiv;


/**
 * This element holds details for the exchange rate with one other currency at a particular time.
 * 
 * <p>Java class for RateDataElement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RateDataElement"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Date" type="{http://www.coda.com/efinance/schemas/common}typeDate" minOccurs="0"/&gt;
 *         &lt;element name="Rate" type="{http://www.coda.com/efinance/schemas/common}typeRate"/&gt;
 *         &lt;element name="MultiplyOrDivide" type="{http://www.coda.com/efinance/schemas/common}typeCtMulDiv"/&gt;
 *         &lt;element name="RateScaling" type="{http://www.coda.com/efinance/schemas/common}typeScaling"/&gt;
 *         &lt;element name="ParentType" type="{http://www.coda.com/efinance/schemas/common}typeCtCurParentType"/&gt;
 *         &lt;element name="ParentCode" type="{http://www.coda.com/efinance/schemas/common}typeGeneralCodeB" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RateDataElement", propOrder = {
    "date",
    "rate",
    "multiplyOrDivide",
    "rateScaling",
    "parentType",
    "parentCode"
})
public class RateDataElement
    implements Serializable
{

    @XmlElement(name = "Date")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar date;
    @XmlElement(name = "Rate", required = true)
    protected BigDecimal rate;
    @XmlElement(name = "MultiplyOrDivide", required = true)
    @XmlSchemaType(name = "string")
    protected TypeCtMulDiv multiplyOrDivide;
    @XmlElement(name = "RateScaling")
    protected int rateScaling;
    @XmlElement(name = "ParentType", required = true)
    @XmlSchemaType(name = "string")
    protected TypeCtCurParentType parentType;
    @XmlElement(name = "ParentCode")
    protected String parentCode;

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDate(XMLGregorianCalendar value) {
        this.date = value;
    }

    /**
     * Gets the value of the rate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRate() {
        return rate;
    }

    /**
     * Sets the value of the rate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRate(BigDecimal value) {
        this.rate = value;
    }

    /**
     * Gets the value of the multiplyOrDivide property.
     * 
     * @return
     *     possible object is
     *     {@link TypeCtMulDiv }
     *     
     */
    public TypeCtMulDiv getMultiplyOrDivide() {
        return multiplyOrDivide;
    }

    /**
     * Sets the value of the multiplyOrDivide property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeCtMulDiv }
     *     
     */
    public void setMultiplyOrDivide(TypeCtMulDiv value) {
        this.multiplyOrDivide = value;
    }

    /**
     * Gets the value of the rateScaling property.
     * 
     */
    public int getRateScaling() {
        return rateScaling;
    }

    /**
     * Sets the value of the rateScaling property.
     * 
     */
    public void setRateScaling(int value) {
        this.rateScaling = value;
    }

    /**
     * Gets the value of the parentType property.
     * 
     * @return
     *     possible object is
     *     {@link TypeCtCurParentType }
     *     
     */
    public TypeCtCurParentType getParentType() {
        return parentType;
    }

    /**
     * Sets the value of the parentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeCtCurParentType }
     *     
     */
    public void setParentType(TypeCtCurParentType value) {
        this.parentType = value;
    }

    /**
     * Gets the value of the parentCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentCode() {
        return parentCode;
    }

    /**
     * Sets the value of the parentCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentCode(String value) {
        this.parentCode = value;
    }

}
