//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.03 at 01:45:01 AM EST 
//


package com.coda.common.schemas.homepagetemplatemaster;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.coda.common.schemas.homepagetemplatemaster package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _HomePageTemplateMasterRequest_QNAME = new QName("http://www.coda.com/common/schemas/homepagetemplatemaster", "HomePageTemplateMasterRequest");
    private final static QName _HomePageTemplateMasterResponse_QNAME = new QName("http://www.coda.com/common/schemas/homepagetemplatemaster", "HomePageTemplateMasterResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.coda.common.schemas.homepagetemplatemaster
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link HomePageTemplateMasterRequest }
     * 
     */
    public HomePageTemplateMasterRequest createHomePageTemplateMasterRequest() {
        return new HomePageTemplateMasterRequest();
    }

    /**
     * Create an instance of {@link HomePageTemplateMasterResponse }
     * 
     */
    public HomePageTemplateMasterResponse createHomePageTemplateMasterResponse() {
        return new HomePageTemplateMasterResponse();
    }

    /**
     * Create an instance of {@link ContentProvider }
     * 
     */
    public ContentProvider createContentProvider() {
        return new ContentProvider();
    }

    /**
     * Create an instance of {@link ContentProviders }
     * 
     */
    public ContentProviders createContentProviders() {
        return new ContentProviders();
    }

    /**
     * Create an instance of {@link HomePageTemplate }
     * 
     */
    public HomePageTemplate createHomePageTemplate() {
        return new HomePageTemplate();
    }

    /**
     * Create an instance of {@link AddRequest }
     * 
     */
    public AddRequest createAddRequest() {
        return new AddRequest();
    }

    /**
     * Create an instance of {@link AddRequestVerb }
     * 
     */
    public AddRequestVerb createAddRequestVerb() {
        return new AddRequestVerb();
    }

    /**
     * Create an instance of {@link AddResponse }
     * 
     */
    public AddResponse createAddResponse() {
        return new AddResponse();
    }

    /**
     * Create an instance of {@link AddResponseVerb }
     * 
     */
    public AddResponseVerb createAddResponseVerb() {
        return new AddResponseVerb();
    }

    /**
     * Create an instance of {@link UpdateRequest }
     * 
     */
    public UpdateRequest createUpdateRequest() {
        return new UpdateRequest();
    }

    /**
     * Create an instance of {@link UpdateRequestVerb }
     * 
     */
    public UpdateRequestVerb createUpdateRequestVerb() {
        return new UpdateRequestVerb();
    }

    /**
     * Create an instance of {@link UpdateResponse }
     * 
     */
    public UpdateResponse createUpdateResponse() {
        return new UpdateResponse();
    }

    /**
     * Create an instance of {@link UpdateResponseVerb }
     * 
     */
    public UpdateResponseVerb createUpdateResponseVerb() {
        return new UpdateResponseVerb();
    }

    /**
     * Create an instance of {@link GetRequest }
     * 
     */
    public GetRequest createGetRequest() {
        return new GetRequest();
    }

    /**
     * Create an instance of {@link GetRequestVerb }
     * 
     */
    public GetRequestVerb createGetRequestVerb() {
        return new GetRequestVerb();
    }

    /**
     * Create an instance of {@link GetResponse }
     * 
     */
    public GetResponse createGetResponse() {
        return new GetResponse();
    }

    /**
     * Create an instance of {@link GetResponseVerb }
     * 
     */
    public GetResponseVerb createGetResponseVerb() {
        return new GetResponseVerb();
    }

    /**
     * Create an instance of {@link DeleteRequest }
     * 
     */
    public DeleteRequest createDeleteRequest() {
        return new DeleteRequest();
    }

    /**
     * Create an instance of {@link DeleteRequestVerb }
     * 
     */
    public DeleteRequestVerb createDeleteRequestVerb() {
        return new DeleteRequestVerb();
    }

    /**
     * Create an instance of {@link DeleteResponse }
     * 
     */
    public DeleteResponse createDeleteResponse() {
        return new DeleteResponse();
    }

    /**
     * Create an instance of {@link DeleteResponseVerb }
     * 
     */
    public DeleteResponseVerb createDeleteResponseVerb() {
        return new DeleteResponseVerb();
    }

    /**
     * Create an instance of {@link ListRequest }
     * 
     */
    public ListRequest createListRequest() {
        return new ListRequest();
    }

    /**
     * Create an instance of {@link ListRequestVerb }
     * 
     */
    public ListRequestVerb createListRequestVerb() {
        return new ListRequestVerb();
    }

    /**
     * Create an instance of {@link ListResponse }
     * 
     */
    public ListResponse createListResponse() {
        return new ListResponse();
    }

    /**
     * Create an instance of {@link ListResponseVerb }
     * 
     */
    public ListResponseVerb createListResponseVerb() {
        return new ListResponseVerb();
    }

    /**
     * Create an instance of {@link GetContentProviderListRequest }
     * 
     */
    public GetContentProviderListRequest createGetContentProviderListRequest() {
        return new GetContentProviderListRequest();
    }

    /**
     * Create an instance of {@link GetContentProviderListRequestVerb }
     * 
     */
    public GetContentProviderListRequestVerb createGetContentProviderListRequestVerb() {
        return new GetContentProviderListRequestVerb();
    }

    /**
     * Create an instance of {@link GetContentProviderListResponse }
     * 
     */
    public GetContentProviderListResponse createGetContentProviderListResponse() {
        return new GetContentProviderListResponse();
    }

    /**
     * Create an instance of {@link GetContentProviderListResponseVerb }
     * 
     */
    public GetContentProviderListResponseVerb createGetContentProviderListResponseVerb() {
        return new GetContentProviderListResponseVerb();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HomePageTemplateMasterRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.coda.com/common/schemas/homepagetemplatemaster", name = "HomePageTemplateMasterRequest")
    public JAXBElement<HomePageTemplateMasterRequest> createHomePageTemplateMasterRequest(HomePageTemplateMasterRequest value) {
        return new JAXBElement<HomePageTemplateMasterRequest>(_HomePageTemplateMasterRequest_QNAME, HomePageTemplateMasterRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HomePageTemplateMasterResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.coda.com/common/schemas/homepagetemplatemaster", name = "HomePageTemplateMasterResponse")
    public JAXBElement<HomePageTemplateMasterResponse> createHomePageTemplateMasterResponse(HomePageTemplateMasterResponse value) {
        return new JAXBElement<HomePageTemplateMasterResponse>(_HomePageTemplateMasterResponse_QNAME, HomePageTemplateMasterResponse.class, null, value);
    }

}
