//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.03 at 01:44:17 AM EST 
//


package com.coda.common.schemas.capabilitymaster;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * An item in the functional security list.
 * 
 * <p>Java class for FunctionalSecurityItem complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FunctionalSecurityItem"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="AppNum" type="{http://www.w3.org/2001/XMLSchema}short"/&gt;
 *         &lt;element name="SubAppNum" type="{http://www.w3.org/2001/XMLSchema}short"/&gt;
 *         &lt;element name="Node" type="{http://www.w3.org/2001/XMLSchema}short"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FunctionalSecurityItem", propOrder = {
    "appNum",
    "subAppNum",
    "node"
})
public class FunctionalSecurityItem
    implements Serializable
{

    @XmlElement(name = "AppNum")
    protected short appNum;
    @XmlElement(name = "SubAppNum")
    protected short subAppNum;
    @XmlElement(name = "Node")
    protected short node;

    /**
     * Gets the value of the appNum property.
     * 
     */
    public short getAppNum() {
        return appNum;
    }

    /**
     * Sets the value of the appNum property.
     * 
     */
    public void setAppNum(short value) {
        this.appNum = value;
    }

    /**
     * Gets the value of the subAppNum property.
     * 
     */
    public short getSubAppNum() {
        return subAppNum;
    }

    /**
     * Sets the value of the subAppNum property.
     * 
     */
    public void setSubAppNum(short value) {
        this.subAppNum = value;
    }

    /**
     * Gets the value of the node property.
     * 
     */
    public short getNode() {
        return node;
    }

    /**
     * Sets the value of the node property.
     * 
     */
    public void setNode(short value) {
        this.node = value;
    }

}
