//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.03 at 01:45:22 AM EST 
//


package com.coda.efinance.schemas.common;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import com.coda.efinance.schemas.country.CountryRequest;


/**
 * <p>Java class for ServiceRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ServiceRequest"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="version" type="{http://www.coda.com/efinance/schemas/common}typeVersion" /&gt;
 *       &lt;attribute name="bulkload" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="logtitle" type="{http://www.coda.com/efinance/schemas/common}typeLogTitle" /&gt;
 *       &lt;attribute name="attachments" type="{http://www.coda.com/efinance/schemas/common}typeAttachments" default="none" /&gt;
 *       &lt;attribute name="locale" type="{http://www.coda.com/efinance/schemas/common}typeLocale" /&gt;
 *       &lt;attribute name="origin" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="funcsec" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ServiceRequest")
@XmlSeeAlso({
    CountryRequest.class
})
public class ServiceRequest
    implements Serializable
{

    @XmlAttribute(name = "version")
    protected String version;
    @XmlAttribute(name = "bulkload")
    protected Boolean bulkload;
    @XmlAttribute(name = "logtitle")
    protected String logtitle;
    @XmlAttribute(name = "attachments")
    protected TypeAttachments attachments;
    @XmlAttribute(name = "locale")
    protected String locale;
    @XmlAttribute(name = "origin")
    protected String origin;
    @XmlAttribute(name = "funcsec")
    protected Boolean funcsec;

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the bulkload property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isBulkload() {
        return bulkload;
    }

    /**
     * Sets the value of the bulkload property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBulkload(Boolean value) {
        this.bulkload = value;
    }

    /**
     * Gets the value of the logtitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogtitle() {
        return logtitle;
    }

    /**
     * Sets the value of the logtitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogtitle(String value) {
        this.logtitle = value;
    }

    /**
     * Gets the value of the attachments property.
     * 
     * @return
     *     possible object is
     *     {@link TypeAttachments }
     *     
     */
    public TypeAttachments getAttachments() {
        if (attachments == null) {
            return TypeAttachments.NONE;
        } else {
            return attachments;
        }
    }

    /**
     * Sets the value of the attachments property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeAttachments }
     *     
     */
    public void setAttachments(TypeAttachments value) {
        this.attachments = value;
    }

    /**
     * Gets the value of the locale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocale() {
        return locale;
    }

    /**
     * Sets the value of the locale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocale(String value) {
        this.locale = value;
    }

    /**
     * Gets the value of the origin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrigin() {
        return origin;
    }

    /**
     * Sets the value of the origin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrigin(String value) {
        this.origin = value;
    }

    /**
     * Gets the value of the funcsec property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFuncsec() {
        return funcsec;
    }

    /**
     * Sets the value of the funcsec property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFuncsec(Boolean value) {
        this.funcsec = value;
    }

}
