//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.03 at 01:45:22 AM EST 
//


package com.coda.efinance.schemas.common;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for typeCtICVocab.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="typeCtICVocab"&gt;
 *   &lt;restriction base="{http://www.coda.com/efinance/schemas/common}typeBaseEnum"&gt;
 *     &lt;enumeration value="ic_vocab_none"/&gt;
 *     &lt;enumeration value="ic_vocab_text"/&gt;
 *     &lt;enumeration value="ic_vocab_sending"/&gt;
 *     &lt;enumeration value="ic_vocab_document"/&gt;
 *     &lt;enumeration value="ic_vocab_number"/&gt;
 *     &lt;enumeration value="ic_vocab_docref"/&gt;
 *     &lt;enumeration value="ic_vocab_user"/&gt;
 *     &lt;enumeration value="ic_vocab_yearperiod"/&gt;
 *     &lt;enumeration value="ic_vocab_crossrefelem"/&gt;
 *     &lt;enumeration value="ic_vocab_crossrefname"/&gt;
 *     &lt;enumeration value="ic_vocab_company"/&gt;
 *     &lt;enumeration value="ic_vocab_compname"/&gt;
 *     &lt;enumeration value="ic_vocab_batch"/&gt;
 *     &lt;enumeration value="ic_vocab_orig_cmpcode"/&gt;
 *     &lt;enumeration value="ic_vocab_orig_doccode"/&gt;
 *     &lt;enumeration value="ic_vocab_orig_docnum"/&gt;
 *     &lt;enumeration value="ic_vocab_orig_docref"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "typeCtICVocab")
@XmlEnum
public enum TypeCtICVocab {

    @XmlEnumValue("ic_vocab_none")
    IC_VOCAB_NONE("ic_vocab_none"),
    @XmlEnumValue("ic_vocab_text")
    IC_VOCAB_TEXT("ic_vocab_text"),
    @XmlEnumValue("ic_vocab_sending")
    IC_VOCAB_SENDING("ic_vocab_sending"),
    @XmlEnumValue("ic_vocab_document")
    IC_VOCAB_DOCUMENT("ic_vocab_document"),
    @XmlEnumValue("ic_vocab_number")
    IC_VOCAB_NUMBER("ic_vocab_number"),
    @XmlEnumValue("ic_vocab_docref")
    IC_VOCAB_DOCREF("ic_vocab_docref"),
    @XmlEnumValue("ic_vocab_user")
    IC_VOCAB_USER("ic_vocab_user"),
    @XmlEnumValue("ic_vocab_yearperiod")
    IC_VOCAB_YEARPERIOD("ic_vocab_yearperiod"),
    @XmlEnumValue("ic_vocab_crossrefelem")
    IC_VOCAB_CROSSREFELEM("ic_vocab_crossrefelem"),
    @XmlEnumValue("ic_vocab_crossrefname")
    IC_VOCAB_CROSSREFNAME("ic_vocab_crossrefname"),
    @XmlEnumValue("ic_vocab_company")
    IC_VOCAB_COMPANY("ic_vocab_company"),
    @XmlEnumValue("ic_vocab_compname")
    IC_VOCAB_COMPNAME("ic_vocab_compname"),
    @XmlEnumValue("ic_vocab_batch")
    IC_VOCAB_BATCH("ic_vocab_batch"),
    @XmlEnumValue("ic_vocab_orig_cmpcode")
    IC_VOCAB_ORIG_CMPCODE("ic_vocab_orig_cmpcode"),
    @XmlEnumValue("ic_vocab_orig_doccode")
    IC_VOCAB_ORIG_DOCCODE("ic_vocab_orig_doccode"),
    @XmlEnumValue("ic_vocab_orig_docnum")
    IC_VOCAB_ORIG_DOCNUM("ic_vocab_orig_docnum"),
    @XmlEnumValue("ic_vocab_orig_docref")
    IC_VOCAB_ORIG_DOCREF("ic_vocab_orig_docref");
    private final String value;

    TypeCtICVocab(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TypeCtICVocab fromValue(String v) {
        for (TypeCtICVocab c: TypeCtICVocab.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
