//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.03 at 01:45:22 AM EST 
//


package com.coda.efinance.schemas.common;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for typeCtPayDocNumStat.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="typeCtPayDocNumStat"&gt;
 *   &lt;restriction base="{http://www.coda.com/efinance/schemas/common}typeBaseEnum"&gt;
 *     &lt;enumeration value="good"/&gt;
 *     &lt;enumeration value="scrapped"/&gt;
 *     &lt;enumeration value="void"/&gt;
 *     &lt;enumeration value="reprinted"/&gt;
 *     &lt;enumeration value="lost"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "typeCtPayDocNumStat")
@XmlEnum
public enum TypeCtPayDocNumStat {

    @XmlEnumValue("good")
    GOOD("good"),
    @XmlEnumValue("scrapped")
    SCRAPPED("scrapped"),
    @XmlEnumValue("void")
    VOID("void"),
    @XmlEnumValue("reprinted")
    REPRINTED("reprinted"),
    @XmlEnumValue("lost")
    LOST("lost");
    private final String value;

    TypeCtPayDocNumStat(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TypeCtPayDocNumStat fromValue(String v) {
        for (TypeCtPayDocNumStat c: TypeCtPayDocNumStat.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
