//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.03 at 01:45:22 AM EST 
//


package com.coda.efinance.schemas.common;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for typeComFavouritesLocation.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="typeComFavouritesLocation"&gt;
 *   &lt;restriction base="{http://www.coda.com/efinance/schemas/common}typeBaseEnum"&gt;
 *     &lt;enumeration value="com_fav_loc_browse_report_master"/&gt;
 *     &lt;enumeration value="com_fav_loc_element_master"/&gt;
 *     &lt;enumeration value="com_fav_loc_browse_report_ass_master"/&gt;
 *     &lt;enumeration value="com_fav_loc_browse_report_bbq_master"/&gt;
 *     &lt;enumeration value="com_fav_loc_accsum_elmfinder"/&gt;
 *     &lt;enumeration value="com_fav_loc_run_asset_browse_report_master"/&gt;
 *     &lt;enumeration value="com_fav_loc_run_browse_report_master"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "typeComFavouritesLocation")
@XmlEnum
public enum TypeComFavouritesLocation {

    @XmlEnumValue("com_fav_loc_browse_report_master")
    COM_FAV_LOC_BROWSE_REPORT_MASTER("com_fav_loc_browse_report_master"),
    @XmlEnumValue("com_fav_loc_element_master")
    COM_FAV_LOC_ELEMENT_MASTER("com_fav_loc_element_master"),
    @XmlEnumValue("com_fav_loc_browse_report_ass_master")
    COM_FAV_LOC_BROWSE_REPORT_ASS_MASTER("com_fav_loc_browse_report_ass_master"),
    @XmlEnumValue("com_fav_loc_browse_report_bbq_master")
    COM_FAV_LOC_BROWSE_REPORT_BBQ_MASTER("com_fav_loc_browse_report_bbq_master"),
    @XmlEnumValue("com_fav_loc_accsum_elmfinder")
    COM_FAV_LOC_ACCSUM_ELMFINDER("com_fav_loc_accsum_elmfinder"),
    @XmlEnumValue("com_fav_loc_run_asset_browse_report_master")
    COM_FAV_LOC_RUN_ASSET_BROWSE_REPORT_MASTER("com_fav_loc_run_asset_browse_report_master"),
    @XmlEnumValue("com_fav_loc_run_browse_report_master")
    COM_FAV_LOC_RUN_BROWSE_REPORT_MASTER("com_fav_loc_run_browse_report_master");
    private final String value;

    TypeComFavouritesLocation(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TypeComFavouritesLocation fromValue(String v) {
        for (TypeComFavouritesLocation c: TypeComFavouritesLocation.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
