//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.03 at 01:45:22 AM EST 
//


package com.coda.efinance.schemas.common;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for typeCtICStatus.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="typeCtICStatus"&gt;
 *   &lt;restriction base="{http://www.coda.com/efinance/schemas/common}typeBaseEnum"&gt;
 *     &lt;enumeration value="ic_status_none"/&gt;
 *     &lt;enumeration value="ic_status_sending"/&gt;
 *     &lt;enumeration value="ic_status_receiving"/&gt;
 *     &lt;enumeration value="ic_status_both"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "typeCtICStatus")
@XmlEnum
public enum TypeCtICStatus {


    /**
     * The document has no InterCompany status.
     * 
     */
    @XmlEnumValue("ic_status_none")
    IC_STATUS_NONE("ic_status_none"),

    /**
     * The document is an InterCompany sending document.
     * 
     */
    @XmlEnumValue("ic_status_sending")
    IC_STATUS_SENDING("ic_status_sending"),

    /**
     * The document is an InterCompany receiving document.
     * 
     */
    @XmlEnumValue("ic_status_receiving")
    IC_STATUS_RECEIVING("ic_status_receiving"),

    /**
     * The document is both a sending and a receiving InterCompany document.
     * 
     */
    @XmlEnumValue("ic_status_both")
    IC_STATUS_BOTH("ic_status_both");
    private final String value;

    TypeCtICStatus(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TypeCtICStatus fromValue(String v) {
        for (TypeCtICStatus c: TypeCtICStatus.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
