//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.03 at 01:45:22 AM EST 
//


package com.coda.efinance.schemas.common;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for typeSchedulerIntervaltype.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="typeSchedulerIntervaltype"&gt;
 *   &lt;restriction base="{http://www.coda.com/efinance/schemas/common}typeBaseEnum"&gt;
 *     &lt;enumeration value="scheduler_intervaltype_minutes"/&gt;
 *     &lt;enumeration value="scheduler_intervaltype_hours"/&gt;
 *     &lt;enumeration value="scheduler_intervaltype_days"/&gt;
 *     &lt;enumeration value="scheduler_intervaltype_weeks"/&gt;
 *     &lt;enumeration value="scheduler_intervaltype_months"/&gt;
 *     &lt;enumeration value="scheduler_intervaltype_periods"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "typeSchedulerIntervaltype")
@XmlEnum
public enum TypeSchedulerIntervaltype {

    @XmlEnumValue("scheduler_intervaltype_minutes")
    SCHEDULER_INTERVALTYPE_MINUTES("scheduler_intervaltype_minutes"),
    @XmlEnumValue("scheduler_intervaltype_hours")
    SCHEDULER_INTERVALTYPE_HOURS("scheduler_intervaltype_hours"),
    @XmlEnumValue("scheduler_intervaltype_days")
    SCHEDULER_INTERVALTYPE_DAYS("scheduler_intervaltype_days"),
    @XmlEnumValue("scheduler_intervaltype_weeks")
    SCHEDULER_INTERVALTYPE_WEEKS("scheduler_intervaltype_weeks"),
    @XmlEnumValue("scheduler_intervaltype_months")
    SCHEDULER_INTERVALTYPE_MONTHS("scheduler_intervaltype_months"),
    @XmlEnumValue("scheduler_intervaltype_periods")
    SCHEDULER_INTERVALTYPE_PERIODS("scheduler_intervaltype_periods");
    private final String value;

    TypeSchedulerIntervaltype(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TypeSchedulerIntervaltype fromValue(String v) {
        for (TypeSchedulerIntervaltype c: TypeSchedulerIntervaltype.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
