//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.03 at 01:45:22 AM EST 
//


package com.coda.efinance.schemas.common;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for typeComUserAlertInterval.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="typeComUserAlertInterval"&gt;
 *   &lt;restriction base="{http://www.coda.com/efinance/schemas/common}typeBaseEnum"&gt;
 *     &lt;enumeration value="com_user_alert_interval_immediate"/&gt;
 *     &lt;enumeration value="com_user_alert_interval_periodic"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "typeComUserAlertInterval")
@XmlEnum
public enum TypeComUserAlertInterval {


    /**
     * Alerts are sent immediately.
     * 
     */
    @XmlEnumValue("com_user_alert_interval_immediate")
    COM_USER_ALERT_INTERVAL_IMMEDIATE("com_user_alert_interval_immediate"),

    /**
     * Alerts are sent according to the specified schedule.
     * 
     */
    @XmlEnumValue("com_user_alert_interval_periodic")
    COM_USER_ALERT_INTERVAL_PERIODIC("com_user_alert_interval_periodic");
    private final String value;

    TypeComUserAlertInterval(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TypeComUserAlertInterval fromValue(String v) {
        for (TypeComUserAlertInterval c: TypeComUserAlertInterval.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
