//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.03 at 01:45:22 AM EST 
//


package com.coda.efinance.schemas.common;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for typeCtAsmElmField.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="typeCtAsmElmField"&gt;
 *   &lt;restriction base="{http://www.coda.com/efinance/schemas/common}typeBaseEnum"&gt;
 *     &lt;enumeration value="elm_code"/&gt;
 *     &lt;enumeration value="vocab_etm_element_name"/&gt;
 *     &lt;enumeration value="vocab_etm_element_short_name"/&gt;
 *     &lt;enumeration value="elm_level"/&gt;
 *     &lt;enumeration value="vocab_etm_credit_limit"/&gt;
 *     &lt;enumeration value="vocab_etm_element_currency"/&gt;
 *     &lt;enumeration value="vocab_etm_credit_limit_date"/&gt;
 *     &lt;enumeration value="vocab_etm_credit_limit_currency"/&gt;
 *     &lt;enumeration value="next_pay_number"/&gt;
 *     &lt;enumeration value="vocab_etm_payment_status"/&gt;
 *     &lt;enumeration value="master_elmstat"/&gt;
 *     &lt;enumeration value="vocab_etm_normal_terms"/&gt;
 *     &lt;enumeration value="vocab_etm_discount_code_1"/&gt;
 *     &lt;enumeration value="vocab_etm_discount_code_2"/&gt;
 *     &lt;enumeration value="vocab_etm_discount_code_3"/&gt;
 *     &lt;enumeration value="vocab_etm_discount_code_4"/&gt;
 *     &lt;enumeration value="vocab_etm_discount_code_5"/&gt;
 *     &lt;enumeration value="vocab_etm_discount_percent_1"/&gt;
 *     &lt;enumeration value="vocab_etm_discount_percent_2"/&gt;
 *     &lt;enumeration value="vocab_etm_discount_percent_3"/&gt;
 *     &lt;enumeration value="vocab_etm_discount_percent_4"/&gt;
 *     &lt;enumeration value="vocab_etm_discount_percent_5"/&gt;
 *     &lt;enumeration value="vocab_etm_standard_industry_code"/&gt;
 *     &lt;enumeration value="vocab_etm_credit_manager"/&gt;
 *     &lt;enumeration value="vocab_etm_credit_rating"/&gt;
 *     &lt;enumeration value="vocab_etm_credit_rating_date"/&gt;
 *     &lt;enumeration value="vocab_etm_credit_reference"/&gt;
 *     &lt;enumeration value="vocab_etm_credit_agency"/&gt;
 *     &lt;enumeration value="date_account_opened"/&gt;
 *     &lt;enumeration value="vocab_etm_payment_index"/&gt;
 *     &lt;enumeration value="last_invoice_code"/&gt;
 *     &lt;enumeration value="last_invoice_number"/&gt;
 *     &lt;enumeration value="last_invoice_date"/&gt;
 *     &lt;enumeration value="last_invoice_pay_status"/&gt;
 *     &lt;enumeration value="last_invoice_currency"/&gt;
 *     &lt;enumeration value="last_invoice_value"/&gt;
 *     &lt;enumeration value="last_payment_code"/&gt;
 *     &lt;enumeration value="last_payment_number"/&gt;
 *     &lt;enumeration value="last_payment_date"/&gt;
 *     &lt;enumeration value="last_payment_pay_status"/&gt;
 *     &lt;enumeration value="last_payment_currency"/&gt;
 *     &lt;enumeration value="last_payment_value"/&gt;
 *     &lt;enumeration value="vocab_etm_address_name"/&gt;
 *     &lt;enumeration value="vocab_etm_address_line_1"/&gt;
 *     &lt;enumeration value="vocab_etm_address_line_2"/&gt;
 *     &lt;enumeration value="vocab_etm_address_line_3"/&gt;
 *     &lt;enumeration value="vocab_etm_address_line_4"/&gt;
 *     &lt;enumeration value="vocab_etm_address_line_5"/&gt;
 *     &lt;enumeration value="vocab_etm_address_line_6"/&gt;
 *     &lt;enumeration value="vocab_etm_post_code"/&gt;
 *     &lt;enumeration value="vocab_etm_telephone"/&gt;
 *     &lt;enumeration value="vocab_etm_fax"/&gt;
 *     &lt;enumeration value="vocab_etm_country_code"/&gt;
 *     &lt;enumeration value="vocab_etm_language_code"/&gt;
 *     &lt;enumeration value="vocab_etm_e_mail"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "typeCtAsmElmField")
@XmlEnum
public enum TypeCtAsmElmField {

    @XmlEnumValue("elm_code")
    ELM_CODE("elm_code"),
    @XmlEnumValue("vocab_etm_element_name")
    VOCAB_ETM_ELEMENT_NAME("vocab_etm_element_name"),
    @XmlEnumValue("vocab_etm_element_short_name")
    VOCAB_ETM_ELEMENT_SHORT_NAME("vocab_etm_element_short_name"),
    @XmlEnumValue("elm_level")
    ELM_LEVEL("elm_level"),
    @XmlEnumValue("vocab_etm_credit_limit")
    VOCAB_ETM_CREDIT_LIMIT("vocab_etm_credit_limit"),
    @XmlEnumValue("vocab_etm_element_currency")
    VOCAB_ETM_ELEMENT_CURRENCY("vocab_etm_element_currency"),
    @XmlEnumValue("vocab_etm_credit_limit_date")
    VOCAB_ETM_CREDIT_LIMIT_DATE("vocab_etm_credit_limit_date"),
    @XmlEnumValue("vocab_etm_credit_limit_currency")
    VOCAB_ETM_CREDIT_LIMIT_CURRENCY("vocab_etm_credit_limit_currency"),
    @XmlEnumValue("next_pay_number")
    NEXT_PAY_NUMBER("next_pay_number"),
    @XmlEnumValue("vocab_etm_payment_status")
    VOCAB_ETM_PAYMENT_STATUS("vocab_etm_payment_status"),
    @XmlEnumValue("master_elmstat")
    MASTER_ELMSTAT("master_elmstat"),
    @XmlEnumValue("vocab_etm_normal_terms")
    VOCAB_ETM_NORMAL_TERMS("vocab_etm_normal_terms"),
    @XmlEnumValue("vocab_etm_discount_code_1")
    VOCAB_ETM_DISCOUNT_CODE_1("vocab_etm_discount_code_1"),
    @XmlEnumValue("vocab_etm_discount_code_2")
    VOCAB_ETM_DISCOUNT_CODE_2("vocab_etm_discount_code_2"),
    @XmlEnumValue("vocab_etm_discount_code_3")
    VOCAB_ETM_DISCOUNT_CODE_3("vocab_etm_discount_code_3"),
    @XmlEnumValue("vocab_etm_discount_code_4")
    VOCAB_ETM_DISCOUNT_CODE_4("vocab_etm_discount_code_4"),
    @XmlEnumValue("vocab_etm_discount_code_5")
    VOCAB_ETM_DISCOUNT_CODE_5("vocab_etm_discount_code_5"),
    @XmlEnumValue("vocab_etm_discount_percent_1")
    VOCAB_ETM_DISCOUNT_PERCENT_1("vocab_etm_discount_percent_1"),
    @XmlEnumValue("vocab_etm_discount_percent_2")
    VOCAB_ETM_DISCOUNT_PERCENT_2("vocab_etm_discount_percent_2"),
    @XmlEnumValue("vocab_etm_discount_percent_3")
    VOCAB_ETM_DISCOUNT_PERCENT_3("vocab_etm_discount_percent_3"),
    @XmlEnumValue("vocab_etm_discount_percent_4")
    VOCAB_ETM_DISCOUNT_PERCENT_4("vocab_etm_discount_percent_4"),
    @XmlEnumValue("vocab_etm_discount_percent_5")
    VOCAB_ETM_DISCOUNT_PERCENT_5("vocab_etm_discount_percent_5"),
    @XmlEnumValue("vocab_etm_standard_industry_code")
    VOCAB_ETM_STANDARD_INDUSTRY_CODE("vocab_etm_standard_industry_code"),
    @XmlEnumValue("vocab_etm_credit_manager")
    VOCAB_ETM_CREDIT_MANAGER("vocab_etm_credit_manager"),
    @XmlEnumValue("vocab_etm_credit_rating")
    VOCAB_ETM_CREDIT_RATING("vocab_etm_credit_rating"),
    @XmlEnumValue("vocab_etm_credit_rating_date")
    VOCAB_ETM_CREDIT_RATING_DATE("vocab_etm_credit_rating_date"),
    @XmlEnumValue("vocab_etm_credit_reference")
    VOCAB_ETM_CREDIT_REFERENCE("vocab_etm_credit_reference"),
    @XmlEnumValue("vocab_etm_credit_agency")
    VOCAB_ETM_CREDIT_AGENCY("vocab_etm_credit_agency"),
    @XmlEnumValue("date_account_opened")
    DATE_ACCOUNT_OPENED("date_account_opened"),
    @XmlEnumValue("vocab_etm_payment_index")
    VOCAB_ETM_PAYMENT_INDEX("vocab_etm_payment_index"),
    @XmlEnumValue("last_invoice_code")
    LAST_INVOICE_CODE("last_invoice_code"),
    @XmlEnumValue("last_invoice_number")
    LAST_INVOICE_NUMBER("last_invoice_number"),
    @XmlEnumValue("last_invoice_date")
    LAST_INVOICE_DATE("last_invoice_date"),
    @XmlEnumValue("last_invoice_pay_status")
    LAST_INVOICE_PAY_STATUS("last_invoice_pay_status"),
    @XmlEnumValue("last_invoice_currency")
    LAST_INVOICE_CURRENCY("last_invoice_currency"),
    @XmlEnumValue("last_invoice_value")
    LAST_INVOICE_VALUE("last_invoice_value"),
    @XmlEnumValue("last_payment_code")
    LAST_PAYMENT_CODE("last_payment_code"),
    @XmlEnumValue("last_payment_number")
    LAST_PAYMENT_NUMBER("last_payment_number"),
    @XmlEnumValue("last_payment_date")
    LAST_PAYMENT_DATE("last_payment_date"),
    @XmlEnumValue("last_payment_pay_status")
    LAST_PAYMENT_PAY_STATUS("last_payment_pay_status"),
    @XmlEnumValue("last_payment_currency")
    LAST_PAYMENT_CURRENCY("last_payment_currency"),
    @XmlEnumValue("last_payment_value")
    LAST_PAYMENT_VALUE("last_payment_value"),
    @XmlEnumValue("vocab_etm_address_name")
    VOCAB_ETM_ADDRESS_NAME("vocab_etm_address_name"),
    @XmlEnumValue("vocab_etm_address_line_1")
    VOCAB_ETM_ADDRESS_LINE_1("vocab_etm_address_line_1"),
    @XmlEnumValue("vocab_etm_address_line_2")
    VOCAB_ETM_ADDRESS_LINE_2("vocab_etm_address_line_2"),
    @XmlEnumValue("vocab_etm_address_line_3")
    VOCAB_ETM_ADDRESS_LINE_3("vocab_etm_address_line_3"),
    @XmlEnumValue("vocab_etm_address_line_4")
    VOCAB_ETM_ADDRESS_LINE_4("vocab_etm_address_line_4"),
    @XmlEnumValue("vocab_etm_address_line_5")
    VOCAB_ETM_ADDRESS_LINE_5("vocab_etm_address_line_5"),
    @XmlEnumValue("vocab_etm_address_line_6")
    VOCAB_ETM_ADDRESS_LINE_6("vocab_etm_address_line_6"),
    @XmlEnumValue("vocab_etm_post_code")
    VOCAB_ETM_POST_CODE("vocab_etm_post_code"),
    @XmlEnumValue("vocab_etm_telephone")
    VOCAB_ETM_TELEPHONE("vocab_etm_telephone"),
    @XmlEnumValue("vocab_etm_fax")
    VOCAB_ETM_FAX("vocab_etm_fax"),
    @XmlEnumValue("vocab_etm_country_code")
    VOCAB_ETM_COUNTRY_CODE("vocab_etm_country_code"),
    @XmlEnumValue("vocab_etm_language_code")
    VOCAB_ETM_LANGUAGE_CODE("vocab_etm_language_code"),
    @XmlEnumValue("vocab_etm_e_mail")
    VOCAB_ETM_E_MAIL("vocab_etm_e_mail");
    private final String value;

    TypeCtAsmElmField(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TypeCtAsmElmField fromValue(String v) {
        for (TypeCtAsmElmField c: TypeCtAsmElmField.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
