//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.03 at 01:45:22 AM EST 
//


package com.coda.efinance.schemas.common;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for typeCtHimGrpType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="typeCtHimGrpType"&gt;
 *   &lt;restriction base="{http://www.coda.com/efinance/schemas/common}typeBaseEnum"&gt;
 *     &lt;enumeration value="him_grptype_accgrp"/&gt;
 *     &lt;enumeration value="him_grptype_elmgrp"/&gt;
 *     &lt;enumeration value="him_elm"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "typeCtHimGrpType")
@XmlEnum
public enum TypeCtHimGrpType {

    @XmlEnumValue("him_grptype_accgrp")
    HIM_GRPTYPE_ACCGRP("him_grptype_accgrp"),
    @XmlEnumValue("him_grptype_elmgrp")
    HIM_GRPTYPE_ELMGRP("him_grptype_elmgrp"),
    @XmlEnumValue("him_elm")
    HIM_ELM("him_elm");
    private final String value;

    TypeCtHimGrpType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TypeCtHimGrpType fromValue(String v) {
        for (TypeCtHimGrpType c: TypeCtHimGrpType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
