//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.03 at 01:45:22 AM EST 
//


package com.coda.efinance.schemas.common;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for typeCtARCBal.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="typeCtARCBal"&gt;
 *   &lt;restriction base="{http://www.coda.com/efinance/schemas/common}typeBaseEnum"&gt;
 *     &lt;enumeration value="arc_bal_none"/&gt;
 *     &lt;enumeration value="arc_bal_coda_only"/&gt;
 *     &lt;enumeration value="arc_bal_all"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "typeCtARCBal")
@XmlEnum
public enum TypeCtARCBal {


    /**
     * None.
     * 
     */
    @XmlEnumValue("arc_bal_none")
    ARC_BAL_NONE("arc_bal_none"),

    /**
     * CODA-maintained balances only.
     * 
     */
    @XmlEnumValue("arc_bal_coda_only")
    ARC_BAL_CODA_ONLY("arc_bal_coda_only"),

    /**
     * All balances.
     * 
     */
    @XmlEnumValue("arc_bal_all")
    ARC_BAL_ALL("arc_bal_all");
    private final String value;

    TypeCtARCBal(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TypeCtARCBal fromValue(String v) {
        for (TypeCtARCBal c: TypeCtARCBal.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
