//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.03 at 01:45:22 AM EST 
//


package com.coda.efinance.schemas.common;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for typeDataMetadataChecksumColumn.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="typeDataMetadataChecksumColumn"&gt;
 *   &lt;restriction base="{http://www.coda.com/efinance/schemas/common}typeBaseEnum"&gt;
 *     &lt;enumeration value="data_metadata_checksum_none"/&gt;
 *     &lt;enumeration value="data_metadata_checksum_column"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "typeDataMetadataChecksumColumn")
@XmlEnum
public enum TypeDataMetadataChecksumColumn {

    @XmlEnumValue("data_metadata_checksum_none")
    DATA_METADATA_CHECKSUM_NONE("data_metadata_checksum_none"),
    @XmlEnumValue("data_metadata_checksum_column")
    DATA_METADATA_CHECKSUM_COLUMN("data_metadata_checksum_column");
    private final String value;

    TypeDataMetadataChecksumColumn(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TypeDataMetadataChecksumColumn fromValue(String v) {
        for (TypeDataMetadataChecksumColumn c: TypeDataMetadataChecksumColumn.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
