//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.03 at 01:45:22 AM EST 
//


package com.coda.efinance.schemas.common;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for typeCtARCOptions.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="typeCtARCOptions"&gt;
 *   &lt;restriction base="{http://www.coda.com/efinance/schemas/common}typeBaseEnum"&gt;
 *     &lt;enumeration value="arc_no_allow_override"/&gt;
 *     &lt;enumeration value="yes"/&gt;
 *     &lt;enumeration value="no"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "typeCtARCOptions")
@XmlEnum
public enum TypeCtARCOptions {


    /**
     * No, but allow another element to override this
     * 
     */
    @XmlEnumValue("arc_no_allow_override")
    ARC_NO_ALLOW_OVERRIDE("arc_no_allow_override"),

    /**
     * Yes
     * 
     */
    @XmlEnumValue("yes")
    YES("yes"),

    /**
     * No (irrespective of other elements)
     * 
     */
    @XmlEnumValue("no")
    NO("no");
    private final String value;

    TypeCtARCOptions(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TypeCtARCOptions fromValue(String v) {
        for (TypeCtARCOptions c: TypeCtARCOptions.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
