//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.03 at 01:45:22 AM EST 
//


package com.coda.efinance.schemas.common;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for typeSecurityReportsFinancialAbilities.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="typeSecurityReportsFinancialAbilities"&gt;
 *   &lt;restriction base="{http://www.coda.com/efinance/schemas/common}typeBaseEnum"&gt;
 *     &lt;enumeration value="sec_reports_inp_can_create_temp_elm"/&gt;
 *     &lt;enumeration value="sec_reports_inp_can_modify_temp_elm"/&gt;
 *     &lt;enumeration value="sec_reports_inp_can_modify_workflow"/&gt;
 *     &lt;enumeration value="sec_reports_inp_can_delete_intray_docs"/&gt;
 *     &lt;enumeration value="sec_reports_inp_can_modify_intray_docs"/&gt;
 *     &lt;enumeration value="sec_reports_inp_can_create_inter_post"/&gt;
 *     &lt;enumeration value="sec_reports_inp_can_use_out_of_period"/&gt;
 *     &lt;enumeration value="sec_reports_inp_can_break_triangulation"/&gt;
 *     &lt;enumeration value="sec_reports_inp_line_value_limit"/&gt;
 *     &lt;enumeration value="sec_reports_pay_can_lock_elms"/&gt;
 *     &lt;enumeration value="sec_reports_pay_can_post_payments"/&gt;
 *     &lt;enumeration value="sec_reports_pay_can_suppress_payments"/&gt;
 *     &lt;enumeration value="sec_reports_pay_can_modify_pmt_proposals"/&gt;
 *     &lt;enumeration value="sec_reports_pay_can_perform_deferred_pmts"/&gt;
 *     &lt;enumeration value="sec_reports_pay_can_run_pmts"/&gt;
 *     &lt;enumeration value="sec_reports_pay_can_run_collections"/&gt;
 *     &lt;enumeration value="sec_reports_browse_can_modify_doc_desc"/&gt;
 *     &lt;enumeration value="sec_reports_browse_can_modify_value_date"/&gt;
 *     &lt;enumeration value="sec_reports_browse_can_modify_due_date"/&gt;
 *     &lt;enumeration value="sec_reports_browse_can_hold_lines"/&gt;
 *     &lt;enumeration value="sec_reports_browse_can_free_held_lines"/&gt;
 *     &lt;enumeration value="sec_reports_browse_can_modify_ext_refs"/&gt;
 *     &lt;enumeration value="sec_reports_browse_can_modify_reminder_sev"/&gt;
 *     &lt;enumeration value="sec_reports_browse_can_modify_recon_stat"/&gt;
 *     &lt;enumeration value="sec_reports_match_can_modify_undo_match_date"/&gt;
 *     &lt;enumeration value="sec_reports_match_can_recon_intray_docs"/&gt;
 *     &lt;enumeration value="sec_reports_match_can_modify_woff_accs"/&gt;
 *     &lt;enumeration value="sec_reports_match_can_modify_disc_accs"/&gt;
 *     &lt;enumeration value="sec_reports_match_can_modify_curr_woff_accs"/&gt;
 *     &lt;enumeration value="sec_reports_discount_variation_limit"/&gt;
 *     &lt;enumeration value="sec_reports_curr_can_modify_exchange_rates"/&gt;
 *     &lt;enumeration value="sec_reports_curr_can_modify_dual_rates"/&gt;
 *     &lt;enumeration value="sec_reports_curr_rate_variation_limit"/&gt;
 *     &lt;enumeration value="sec_reports_archive_can_suppress_arc_jnls"/&gt;
 *     &lt;enumeration value="sec_reports_archive_can_arc_balances"/&gt;
 *     &lt;enumeration value="sec_reports_company_can_modify_bal_elms"/&gt;
 *     &lt;enumeration value="sec_reports_tax_variation_limit"/&gt;
 *     &lt;enumeration value="sec_reports_period_security_grp"/&gt;
 *     &lt;enumeration value="sec_reports_password_expiry_disabled"/&gt;
 *     &lt;enumeration value="sec_reports_workflow_auth_limit"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "typeSecurityReportsFinancialAbilities")
@XmlEnum
public enum TypeSecurityReportsFinancialAbilities {

    @XmlEnumValue("sec_reports_inp_can_create_temp_elm")
    SEC_REPORTS_INP_CAN_CREATE_TEMP_ELM("sec_reports_inp_can_create_temp_elm"),
    @XmlEnumValue("sec_reports_inp_can_modify_temp_elm")
    SEC_REPORTS_INP_CAN_MODIFY_TEMP_ELM("sec_reports_inp_can_modify_temp_elm"),
    @XmlEnumValue("sec_reports_inp_can_modify_workflow")
    SEC_REPORTS_INP_CAN_MODIFY_WORKFLOW("sec_reports_inp_can_modify_workflow"),
    @XmlEnumValue("sec_reports_inp_can_delete_intray_docs")
    SEC_REPORTS_INP_CAN_DELETE_INTRAY_DOCS("sec_reports_inp_can_delete_intray_docs"),
    @XmlEnumValue("sec_reports_inp_can_modify_intray_docs")
    SEC_REPORTS_INP_CAN_MODIFY_INTRAY_DOCS("sec_reports_inp_can_modify_intray_docs"),
    @XmlEnumValue("sec_reports_inp_can_create_inter_post")
    SEC_REPORTS_INP_CAN_CREATE_INTER_POST("sec_reports_inp_can_create_inter_post"),
    @XmlEnumValue("sec_reports_inp_can_use_out_of_period")
    SEC_REPORTS_INP_CAN_USE_OUT_OF_PERIOD("sec_reports_inp_can_use_out_of_period"),
    @XmlEnumValue("sec_reports_inp_can_break_triangulation")
    SEC_REPORTS_INP_CAN_BREAK_TRIANGULATION("sec_reports_inp_can_break_triangulation"),
    @XmlEnumValue("sec_reports_inp_line_value_limit")
    SEC_REPORTS_INP_LINE_VALUE_LIMIT("sec_reports_inp_line_value_limit"),
    @XmlEnumValue("sec_reports_pay_can_lock_elms")
    SEC_REPORTS_PAY_CAN_LOCK_ELMS("sec_reports_pay_can_lock_elms"),
    @XmlEnumValue("sec_reports_pay_can_post_payments")
    SEC_REPORTS_PAY_CAN_POST_PAYMENTS("sec_reports_pay_can_post_payments"),
    @XmlEnumValue("sec_reports_pay_can_suppress_payments")
    SEC_REPORTS_PAY_CAN_SUPPRESS_PAYMENTS("sec_reports_pay_can_suppress_payments"),
    @XmlEnumValue("sec_reports_pay_can_modify_pmt_proposals")
    SEC_REPORTS_PAY_CAN_MODIFY_PMT_PROPOSALS("sec_reports_pay_can_modify_pmt_proposals"),
    @XmlEnumValue("sec_reports_pay_can_perform_deferred_pmts")
    SEC_REPORTS_PAY_CAN_PERFORM_DEFERRED_PMTS("sec_reports_pay_can_perform_deferred_pmts"),
    @XmlEnumValue("sec_reports_pay_can_run_pmts")
    SEC_REPORTS_PAY_CAN_RUN_PMTS("sec_reports_pay_can_run_pmts"),
    @XmlEnumValue("sec_reports_pay_can_run_collections")
    SEC_REPORTS_PAY_CAN_RUN_COLLECTIONS("sec_reports_pay_can_run_collections"),
    @XmlEnumValue("sec_reports_browse_can_modify_doc_desc")
    SEC_REPORTS_BROWSE_CAN_MODIFY_DOC_DESC("sec_reports_browse_can_modify_doc_desc"),
    @XmlEnumValue("sec_reports_browse_can_modify_value_date")
    SEC_REPORTS_BROWSE_CAN_MODIFY_VALUE_DATE("sec_reports_browse_can_modify_value_date"),
    @XmlEnumValue("sec_reports_browse_can_modify_due_date")
    SEC_REPORTS_BROWSE_CAN_MODIFY_DUE_DATE("sec_reports_browse_can_modify_due_date"),
    @XmlEnumValue("sec_reports_browse_can_hold_lines")
    SEC_REPORTS_BROWSE_CAN_HOLD_LINES("sec_reports_browse_can_hold_lines"),
    @XmlEnumValue("sec_reports_browse_can_free_held_lines")
    SEC_REPORTS_BROWSE_CAN_FREE_HELD_LINES("sec_reports_browse_can_free_held_lines"),
    @XmlEnumValue("sec_reports_browse_can_modify_ext_refs")
    SEC_REPORTS_BROWSE_CAN_MODIFY_EXT_REFS("sec_reports_browse_can_modify_ext_refs"),
    @XmlEnumValue("sec_reports_browse_can_modify_reminder_sev")
    SEC_REPORTS_BROWSE_CAN_MODIFY_REMINDER_SEV("sec_reports_browse_can_modify_reminder_sev"),
    @XmlEnumValue("sec_reports_browse_can_modify_recon_stat")
    SEC_REPORTS_BROWSE_CAN_MODIFY_RECON_STAT("sec_reports_browse_can_modify_recon_stat"),
    @XmlEnumValue("sec_reports_match_can_modify_undo_match_date")
    SEC_REPORTS_MATCH_CAN_MODIFY_UNDO_MATCH_DATE("sec_reports_match_can_modify_undo_match_date"),
    @XmlEnumValue("sec_reports_match_can_recon_intray_docs")
    SEC_REPORTS_MATCH_CAN_RECON_INTRAY_DOCS("sec_reports_match_can_recon_intray_docs"),
    @XmlEnumValue("sec_reports_match_can_modify_woff_accs")
    SEC_REPORTS_MATCH_CAN_MODIFY_WOFF_ACCS("sec_reports_match_can_modify_woff_accs"),
    @XmlEnumValue("sec_reports_match_can_modify_disc_accs")
    SEC_REPORTS_MATCH_CAN_MODIFY_DISC_ACCS("sec_reports_match_can_modify_disc_accs"),
    @XmlEnumValue("sec_reports_match_can_modify_curr_woff_accs")
    SEC_REPORTS_MATCH_CAN_MODIFY_CURR_WOFF_ACCS("sec_reports_match_can_modify_curr_woff_accs"),
    @XmlEnumValue("sec_reports_discount_variation_limit")
    SEC_REPORTS_DISCOUNT_VARIATION_LIMIT("sec_reports_discount_variation_limit"),
    @XmlEnumValue("sec_reports_curr_can_modify_exchange_rates")
    SEC_REPORTS_CURR_CAN_MODIFY_EXCHANGE_RATES("sec_reports_curr_can_modify_exchange_rates"),
    @XmlEnumValue("sec_reports_curr_can_modify_dual_rates")
    SEC_REPORTS_CURR_CAN_MODIFY_DUAL_RATES("sec_reports_curr_can_modify_dual_rates"),
    @XmlEnumValue("sec_reports_curr_rate_variation_limit")
    SEC_REPORTS_CURR_RATE_VARIATION_LIMIT("sec_reports_curr_rate_variation_limit"),
    @XmlEnumValue("sec_reports_archive_can_suppress_arc_jnls")
    SEC_REPORTS_ARCHIVE_CAN_SUPPRESS_ARC_JNLS("sec_reports_archive_can_suppress_arc_jnls"),
    @XmlEnumValue("sec_reports_archive_can_arc_balances")
    SEC_REPORTS_ARCHIVE_CAN_ARC_BALANCES("sec_reports_archive_can_arc_balances"),
    @XmlEnumValue("sec_reports_company_can_modify_bal_elms")
    SEC_REPORTS_COMPANY_CAN_MODIFY_BAL_ELMS("sec_reports_company_can_modify_bal_elms"),
    @XmlEnumValue("sec_reports_tax_variation_limit")
    SEC_REPORTS_TAX_VARIATION_LIMIT("sec_reports_tax_variation_limit"),
    @XmlEnumValue("sec_reports_period_security_grp")
    SEC_REPORTS_PERIOD_SECURITY_GRP("sec_reports_period_security_grp"),
    @XmlEnumValue("sec_reports_password_expiry_disabled")
    SEC_REPORTS_PASSWORD_EXPIRY_DISABLED("sec_reports_password_expiry_disabled"),
    @XmlEnumValue("sec_reports_workflow_auth_limit")
    SEC_REPORTS_WORKFLOW_AUTH_LIMIT("sec_reports_workflow_auth_limit");
    private final String value;

    TypeSecurityReportsFinancialAbilities(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TypeSecurityReportsFinancialAbilities fromValue(String v) {
        for (TypeSecurityReportsFinancialAbilities c: TypeSecurityReportsFinancialAbilities.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
