//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.03 at 01:45:22 AM EST 
//


package com.coda.efinance.schemas.common;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for typeCtUseLineType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="typeCtUseLineType"&gt;
 *   &lt;restriction base="{http://www.coda.com/efinance/schemas/common}typeBaseEnum"&gt;
 *     &lt;enumeration value="curr_home"/&gt;
 *     &lt;enumeration value="curr_dual"/&gt;
 *     &lt;enumeration value="curr_el1"/&gt;
 *     &lt;enumeration value="curr_el2"/&gt;
 *     &lt;enumeration value="curr_el3"/&gt;
 *     &lt;enumeration value="curr_el4"/&gt;
 *     &lt;enumeration value="curr_el5"/&gt;
 *     &lt;enumeration value="curr_el6"/&gt;
 *     &lt;enumeration value="curr_el7"/&gt;
 *     &lt;enumeration value="curr_el8"/&gt;
 *     &lt;enumeration value="curr_ruling"/&gt;
 *     &lt;enumeration value="curr_account"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "typeCtUseLineType")
@XmlEnum
public enum TypeCtUseLineType {

    @XmlEnumValue("curr_home")
    CURR_HOME("curr_home"),
    @XmlEnumValue("curr_dual")
    CURR_DUAL("curr_dual"),
    @XmlEnumValue("curr_el1")
    CURR_EL_1("curr_el1"),
    @XmlEnumValue("curr_el2")
    CURR_EL_2("curr_el2"),
    @XmlEnumValue("curr_el3")
    CURR_EL_3("curr_el3"),
    @XmlEnumValue("curr_el4")
    CURR_EL_4("curr_el4"),
    @XmlEnumValue("curr_el5")
    CURR_EL_5("curr_el5"),
    @XmlEnumValue("curr_el6")
    CURR_EL_6("curr_el6"),
    @XmlEnumValue("curr_el7")
    CURR_EL_7("curr_el7"),
    @XmlEnumValue("curr_el8")
    CURR_EL_8("curr_el8"),
    @XmlEnumValue("curr_ruling")
    CURR_RULING("curr_ruling"),
    @XmlEnumValue("curr_account")
    CURR_ACCOUNT("curr_account");
    private final String value;

    TypeCtUseLineType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TypeCtUseLineType fromValue(String v) {
        for (TypeCtUseLineType c: TypeCtUseLineType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
