//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.03 at 01:45:22 AM EST 
//


package com.coda.efinance.schemas.common;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for typeCtCurGender.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="typeCtCurGender"&gt;
 *   &lt;restriction base="{http://www.coda.com/efinance/schemas/common}typeBaseEnum"&gt;
 *     &lt;enumeration value="gender_masculine"/&gt;
 *     &lt;enumeration value="gender_feminine"/&gt;
 *     &lt;enumeration value="gender_neuter"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "typeCtCurGender")
@XmlEnum
public enum TypeCtCurGender {


    /**
     * Masculine gender
     * 
     */
    @XmlEnumValue("gender_masculine")
    GENDER_MASCULINE("gender_masculine"),

    /**
     * Feminine gender
     * 
     */
    @XmlEnumValue("gender_feminine")
    GENDER_FEMININE("gender_feminine"),

    /**
     * Neuter gender
     * 
     */
    @XmlEnumValue("gender_neuter")
    GENDER_NEUTER("gender_neuter");
    private final String value;

    TypeCtCurGender(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TypeCtCurGender fromValue(String v) {
        for (TypeCtCurGender c: TypeCtCurGender.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
