//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.03 at 01:45:22 AM EST 
//


package com.coda.efinance.schemas.common;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for typeCtYeaInterval.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="typeCtYeaInterval"&gt;
 *   &lt;restriction base="{http://www.coda.com/efinance/schemas/common}typeBaseEnum"&gt;
 *     &lt;enumeration value="period_months"/&gt;
 *     &lt;enumeration value="period_monthend"/&gt;
 *     &lt;enumeration value="period_days"/&gt;
 *     &lt;enumeration value="period_454"/&gt;
 *     &lt;enumeration value="period_445"/&gt;
 *     &lt;enumeration value="period_544"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "typeCtYeaInterval")
@XmlEnum
public enum TypeCtYeaInterval {

    @XmlEnumValue("period_months")
    PERIOD_MONTHS("period_months"),
    @XmlEnumValue("period_monthend")
    PERIOD_MONTHEND("period_monthend"),
    @XmlEnumValue("period_days")
    PERIOD_DAYS("period_days"),
    @XmlEnumValue("period_454")
    PERIOD_454("period_454"),
    @XmlEnumValue("period_445")
    PERIOD_445("period_445"),
    @XmlEnumValue("period_544")
    PERIOD_544("period_544");
    private final String value;

    TypeCtYeaInterval(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TypeCtYeaInterval fromValue(String v) {
        for (TypeCtYeaInterval c: TypeCtYeaInterval.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
