//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.03 at 01:45:22 AM EST 
//


package com.coda.efinance.schemas.common;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for typeComLeafUnique.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="typeComLeafUnique"&gt;
 *   &lt;restriction base="{http://www.coda.com/efinance/schemas/common}typeBaseEnum"&gt;
 *     &lt;enumeration value="com_leaf_unique_hierarchy"/&gt;
 *     &lt;enumeration value="com_leaf_unique_node"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "typeComLeafUnique")
@XmlEnum
public enum TypeComLeafUnique {

    @XmlEnumValue("com_leaf_unique_hierarchy")
    COM_LEAF_UNIQUE_HIERARCHY("com_leaf_unique_hierarchy"),
    @XmlEnumValue("com_leaf_unique_node")
    COM_LEAF_UNIQUE_NODE("com_leaf_unique_node");
    private final String value;

    TypeComLeafUnique(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TypeComLeafUnique fromValue(String v) {
        for (TypeComLeafUnique c: TypeComLeafUnique.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
