//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.03 at 01:44:24 AM EST 
//


package com.coda.common.schemas.rolemaster;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.coda.efinance.schemas.common.ServiceRequest;


/**
 * This service allows you to maintain role masters.
 * 
 * <p>Java class for RoleMasterRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RoleMasterRequest"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.coda.com/efinance/schemas/common}ServiceRequest"&gt;
 *       &lt;all&gt;
 *         &lt;element name="Add" type="{http://www.coda.com/common/schemas/rolemaster}AddRequestVerb" minOccurs="0"/&gt;
 *         &lt;element name="Update" type="{http://www.coda.com/common/schemas/rolemaster}UpdateRequestVerb" minOccurs="0"/&gt;
 *         &lt;element name="Get" type="{http://www.coda.com/common/schemas/rolemaster}GetRequestVerb" minOccurs="0"/&gt;
 *         &lt;element name="Delete" type="{http://www.coda.com/common/schemas/rolemaster}DeleteRequestVerb" minOccurs="0"/&gt;
 *         &lt;element name="List" type="{http://www.coda.com/common/schemas/rolemaster}ListRequestVerb" minOccurs="0"/&gt;
 *         &lt;element name="Find" type="{http://www.coda.com/common/schemas/rolemaster}FindRequestVerb" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RoleMasterRequest", propOrder = {
    "add",
    "update",
    "get",
    "delete",
    "list",
    "find"
})
public class RoleMasterRequest
    extends ServiceRequest
    implements Serializable
{

    @XmlElement(name = "Add")
    protected AddRequestVerb add;
    @XmlElement(name = "Update")
    protected UpdateRequestVerb update;
    @XmlElement(name = "Get")
    protected GetRequestVerb get;
    @XmlElement(name = "Delete")
    protected DeleteRequestVerb delete;
    @XmlElement(name = "List")
    protected ListRequestVerb list;
    @XmlElement(name = "Find")
    protected FindRequestVerb find;

    /**
     * Gets the value of the add property.
     * 
     * @return
     *     possible object is
     *     {@link AddRequestVerb }
     *     
     */
    public AddRequestVerb getAdd() {
        return add;
    }

    /**
     * Sets the value of the add property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddRequestVerb }
     *     
     */
    public void setAdd(AddRequestVerb value) {
        this.add = value;
    }

    /**
     * Gets the value of the update property.
     * 
     * @return
     *     possible object is
     *     {@link UpdateRequestVerb }
     *     
     */
    public UpdateRequestVerb getUpdate() {
        return update;
    }

    /**
     * Sets the value of the update property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpdateRequestVerb }
     *     
     */
    public void setUpdate(UpdateRequestVerb value) {
        this.update = value;
    }

    /**
     * Gets the value of the get property.
     * 
     * @return
     *     possible object is
     *     {@link GetRequestVerb }
     *     
     */
    public GetRequestVerb getGet() {
        return get;
    }

    /**
     * Sets the value of the get property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetRequestVerb }
     *     
     */
    public void setGet(GetRequestVerb value) {
        this.get = value;
    }

    /**
     * Gets the value of the delete property.
     * 
     * @return
     *     possible object is
     *     {@link DeleteRequestVerb }
     *     
     */
    public DeleteRequestVerb getDelete() {
        return delete;
    }

    /**
     * Sets the value of the delete property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeleteRequestVerb }
     *     
     */
    public void setDelete(DeleteRequestVerb value) {
        this.delete = value;
    }

    /**
     * Gets the value of the list property.
     * 
     * @return
     *     possible object is
     *     {@link ListRequestVerb }
     *     
     */
    public ListRequestVerb getList() {
        return list;
    }

    /**
     * Sets the value of the list property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListRequestVerb }
     *     
     */
    public void setList(ListRequestVerb value) {
        this.list = value;
    }

    /**
     * Gets the value of the find property.
     * 
     * @return
     *     possible object is
     *     {@link FindRequestVerb }
     *     
     */
    public FindRequestVerb getFind() {
        return find;
    }

    /**
     * Sets the value of the find property.
     * 
     * @param value
     *     allowed object is
     *     {@link FindRequestVerb }
     *     
     */
    public void setFind(FindRequestVerb value) {
        this.find = value;
    }

}
