//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.03 at 01:45:08 AM EST 
//


package com.coda.common.schemas.contentprovidermaster;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.coda.efinance.schemas.common.ServiceRequest;


/**
 * This service allows you to maintain content provider masters.
 * 
 * <p>Java class for ContentProviderMasterRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ContentProviderMasterRequest"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.coda.com/efinance/schemas/common}ServiceRequest"&gt;
 *       &lt;all&gt;
 *         &lt;element name="Add" type="{http://www.coda.com/common/schemas/contentprovidermaster}AddRequestVerb" minOccurs="0"/&gt;
 *         &lt;element name="Update" type="{http://www.coda.com/common/schemas/contentprovidermaster}UpdateRequestVerb" minOccurs="0"/&gt;
 *         &lt;element name="Get" type="{http://www.coda.com/common/schemas/contentprovidermaster}GetRequestVerb" minOccurs="0"/&gt;
 *         &lt;element name="Delete" type="{http://www.coda.com/common/schemas/contentprovidermaster}DeleteRequestVerb" minOccurs="0"/&gt;
 *         &lt;element name="List" type="{http://www.coda.com/common/schemas/contentprovidermaster}ListRequestVerb" minOccurs="0"/&gt;
 *         &lt;element name="ListByExtensionCode" type="{http://www.coda.com/common/schemas/contentprovidermaster}ListByExtensionCodeRequestVerb" minOccurs="0"/&gt;
 *         &lt;element name="MatchBySystemParameters" type="{http://www.coda.com/common/schemas/contentprovidermaster}MatchBySystemParametersRequestVerb" minOccurs="0"/&gt;
 *         &lt;element name="InUseByCustomise" type="{http://www.coda.com/common/schemas/contentprovidermaster}InUseByCustomiseRequestVerb" minOccurs="0"/&gt;
 *         &lt;element name="UpdateSystemParameters" type="{http://www.coda.com/common/schemas/contentprovidermaster}UpdateSystemParametersRequestVerb" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ContentProviderMasterRequest", propOrder = {
    "add",
    "update",
    "get",
    "delete",
    "list",
    "listByExtensionCode",
    "matchBySystemParameters",
    "inUseByCustomise",
    "updateSystemParameters"
})
public class ContentProviderMasterRequest
    extends ServiceRequest
    implements Serializable
{

    @XmlElement(name = "Add")
    protected AddRequestVerb add;
    @XmlElement(name = "Update")
    protected UpdateRequestVerb update;
    @XmlElement(name = "Get")
    protected GetRequestVerb get;
    @XmlElement(name = "Delete")
    protected DeleteRequestVerb delete;
    @XmlElement(name = "List")
    protected ListRequestVerb list;
    @XmlElement(name = "ListByExtensionCode")
    protected ListByExtensionCodeRequestVerb listByExtensionCode;
    @XmlElement(name = "MatchBySystemParameters")
    protected MatchBySystemParametersRequestVerb matchBySystemParameters;
    @XmlElement(name = "InUseByCustomise")
    protected InUseByCustomiseRequestVerb inUseByCustomise;
    @XmlElement(name = "UpdateSystemParameters")
    protected UpdateSystemParametersRequestVerb updateSystemParameters;

    /**
     * Gets the value of the add property.
     * 
     * @return
     *     possible object is
     *     {@link AddRequestVerb }
     *     
     */
    public AddRequestVerb getAdd() {
        return add;
    }

    /**
     * Sets the value of the add property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddRequestVerb }
     *     
     */
    public void setAdd(AddRequestVerb value) {
        this.add = value;
    }

    /**
     * Gets the value of the update property.
     * 
     * @return
     *     possible object is
     *     {@link UpdateRequestVerb }
     *     
     */
    public UpdateRequestVerb getUpdate() {
        return update;
    }

    /**
     * Sets the value of the update property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpdateRequestVerb }
     *     
     */
    public void setUpdate(UpdateRequestVerb value) {
        this.update = value;
    }

    /**
     * Gets the value of the get property.
     * 
     * @return
     *     possible object is
     *     {@link GetRequestVerb }
     *     
     */
    public GetRequestVerb getGet() {
        return get;
    }

    /**
     * Sets the value of the get property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetRequestVerb }
     *     
     */
    public void setGet(GetRequestVerb value) {
        this.get = value;
    }

    /**
     * Gets the value of the delete property.
     * 
     * @return
     *     possible object is
     *     {@link DeleteRequestVerb }
     *     
     */
    public DeleteRequestVerb getDelete() {
        return delete;
    }

    /**
     * Sets the value of the delete property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeleteRequestVerb }
     *     
     */
    public void setDelete(DeleteRequestVerb value) {
        this.delete = value;
    }

    /**
     * Gets the value of the list property.
     * 
     * @return
     *     possible object is
     *     {@link ListRequestVerb }
     *     
     */
    public ListRequestVerb getList() {
        return list;
    }

    /**
     * Sets the value of the list property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListRequestVerb }
     *     
     */
    public void setList(ListRequestVerb value) {
        this.list = value;
    }

    /**
     * Gets the value of the listByExtensionCode property.
     * 
     * @return
     *     possible object is
     *     {@link ListByExtensionCodeRequestVerb }
     *     
     */
    public ListByExtensionCodeRequestVerb getListByExtensionCode() {
        return listByExtensionCode;
    }

    /**
     * Sets the value of the listByExtensionCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListByExtensionCodeRequestVerb }
     *     
     */
    public void setListByExtensionCode(ListByExtensionCodeRequestVerb value) {
        this.listByExtensionCode = value;
    }

    /**
     * Gets the value of the matchBySystemParameters property.
     * 
     * @return
     *     possible object is
     *     {@link MatchBySystemParametersRequestVerb }
     *     
     */
    public MatchBySystemParametersRequestVerb getMatchBySystemParameters() {
        return matchBySystemParameters;
    }

    /**
     * Sets the value of the matchBySystemParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link MatchBySystemParametersRequestVerb }
     *     
     */
    public void setMatchBySystemParameters(MatchBySystemParametersRequestVerb value) {
        this.matchBySystemParameters = value;
    }

    /**
     * Gets the value of the inUseByCustomise property.
     * 
     * @return
     *     possible object is
     *     {@link InUseByCustomiseRequestVerb }
     *     
     */
    public InUseByCustomiseRequestVerb getInUseByCustomise() {
        return inUseByCustomise;
    }

    /**
     * Sets the value of the inUseByCustomise property.
     * 
     * @param value
     *     allowed object is
     *     {@link InUseByCustomiseRequestVerb }
     *     
     */
    public void setInUseByCustomise(InUseByCustomiseRequestVerb value) {
        this.inUseByCustomise = value;
    }

    /**
     * Gets the value of the updateSystemParameters property.
     * 
     * @return
     *     possible object is
     *     {@link UpdateSystemParametersRequestVerb }
     *     
     */
    public UpdateSystemParametersRequestVerb getUpdateSystemParameters() {
        return updateSystemParameters;
    }

    /**
     * Sets the value of the updateSystemParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpdateSystemParametersRequestVerb }
     *     
     */
    public void setUpdateSystemParameters(UpdateSystemParametersRequestVerb value) {
        this.updateSystemParameters = value;
    }

}
