//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.03 at 01:43:06 AM EST 
//


package com.coda.efinance.schemas.company;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * This element contains a list of UDFs.
 * 
 * <p>Java class for ItemUDFSettings complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ItemUDFSettings"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="UDF1" type="{http://www.coda.com/efinance/schemas/company}ItemUDFSetting" minOccurs="0"/&gt;
 *         &lt;element name="UDF2" type="{http://www.coda.com/efinance/schemas/company}ItemUDFSetting" minOccurs="0"/&gt;
 *         &lt;element name="UDF3" type="{http://www.coda.com/efinance/schemas/company}ItemUDFSetting" minOccurs="0"/&gt;
 *         &lt;element name="UDF4" type="{http://www.coda.com/efinance/schemas/company}ItemUDFSetting" minOccurs="0"/&gt;
 *         &lt;element name="UDF5" type="{http://www.coda.com/efinance/schemas/company}ItemUDFSetting" minOccurs="0"/&gt;
 *         &lt;element name="UDF6" type="{http://www.coda.com/efinance/schemas/company}ItemUDFSetting" minOccurs="0"/&gt;
 *         &lt;element name="UDF7" type="{http://www.coda.com/efinance/schemas/company}ItemUDFSetting" minOccurs="0"/&gt;
 *         &lt;element name="UDF8" type="{http://www.coda.com/efinance/schemas/company}ItemUDFSetting" minOccurs="0"/&gt;
 *         &lt;element name="UDF9" type="{http://www.coda.com/efinance/schemas/company}ItemUDFSetting" minOccurs="0"/&gt;
 *         &lt;element name="UDF10" type="{http://www.coda.com/efinance/schemas/company}ItemUDFSetting" minOccurs="0"/&gt;
 *         &lt;element name="UDF11" type="{http://www.coda.com/efinance/schemas/company}ItemUDFSetting" minOccurs="0"/&gt;
 *         &lt;element name="UDF12" type="{http://www.coda.com/efinance/schemas/company}ItemUDFSetting" minOccurs="0"/&gt;
 *         &lt;element name="UDF13" type="{http://www.coda.com/efinance/schemas/company}ItemUDFSetting" minOccurs="0"/&gt;
 *         &lt;element name="UDF14" type="{http://www.coda.com/efinance/schemas/company}ItemUDFSetting" minOccurs="0"/&gt;
 *         &lt;element name="UDF15" type="{http://www.coda.com/efinance/schemas/company}ItemUDFSetting" minOccurs="0"/&gt;
 *         &lt;element name="UDF16" type="{http://www.coda.com/efinance/schemas/company}ItemUDFSetting" minOccurs="0"/&gt;
 *         &lt;element name="UDF17" type="{http://www.coda.com/efinance/schemas/company}ItemUDFSetting" minOccurs="0"/&gt;
 *         &lt;element name="UDF18" type="{http://www.coda.com/efinance/schemas/company}ItemUDFSetting" minOccurs="0"/&gt;
 *         &lt;element name="UDF19" type="{http://www.coda.com/efinance/schemas/company}ItemUDFSetting" minOccurs="0"/&gt;
 *         &lt;element name="UDF20" type="{http://www.coda.com/efinance/schemas/company}ItemUDFSetting" minOccurs="0"/&gt;
 *         &lt;element name="UDF21" type="{http://www.coda.com/efinance/schemas/company}ItemUDFSetting" minOccurs="0"/&gt;
 *         &lt;element name="UDF22" type="{http://www.coda.com/efinance/schemas/company}ItemUDFSetting" minOccurs="0"/&gt;
 *         &lt;element name="UDF23" type="{http://www.coda.com/efinance/schemas/company}ItemUDFSetting" minOccurs="0"/&gt;
 *         &lt;element name="UDF24" type="{http://www.coda.com/efinance/schemas/company}ItemUDFSetting" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ItemUDFSettings", propOrder = {
    "udf1",
    "udf2",
    "udf3",
    "udf4",
    "udf5",
    "udf6",
    "udf7",
    "udf8",
    "udf9",
    "udf10",
    "udf11",
    "udf12",
    "udf13",
    "udf14",
    "udf15",
    "udf16",
    "udf17",
    "udf18",
    "udf19",
    "udf20",
    "udf21",
    "udf22",
    "udf23",
    "udf24"
})
public class ItemUDFSettings
    implements Serializable
{

    @XmlElement(name = "UDF1")
    protected ItemUDFSetting udf1;
    @XmlElement(name = "UDF2")
    protected ItemUDFSetting udf2;
    @XmlElement(name = "UDF3")
    protected ItemUDFSetting udf3;
    @XmlElement(name = "UDF4")
    protected ItemUDFSetting udf4;
    @XmlElement(name = "UDF5")
    protected ItemUDFSetting udf5;
    @XmlElement(name = "UDF6")
    protected ItemUDFSetting udf6;
    @XmlElement(name = "UDF7")
    protected ItemUDFSetting udf7;
    @XmlElement(name = "UDF8")
    protected ItemUDFSetting udf8;
    @XmlElement(name = "UDF9")
    protected ItemUDFSetting udf9;
    @XmlElement(name = "UDF10")
    protected ItemUDFSetting udf10;
    @XmlElement(name = "UDF11")
    protected ItemUDFSetting udf11;
    @XmlElement(name = "UDF12")
    protected ItemUDFSetting udf12;
    @XmlElement(name = "UDF13")
    protected ItemUDFSetting udf13;
    @XmlElement(name = "UDF14")
    protected ItemUDFSetting udf14;
    @XmlElement(name = "UDF15")
    protected ItemUDFSetting udf15;
    @XmlElement(name = "UDF16")
    protected ItemUDFSetting udf16;
    @XmlElement(name = "UDF17")
    protected ItemUDFSetting udf17;
    @XmlElement(name = "UDF18")
    protected ItemUDFSetting udf18;
    @XmlElement(name = "UDF19")
    protected ItemUDFSetting udf19;
    @XmlElement(name = "UDF20")
    protected ItemUDFSetting udf20;
    @XmlElement(name = "UDF21")
    protected ItemUDFSetting udf21;
    @XmlElement(name = "UDF22")
    protected ItemUDFSetting udf22;
    @XmlElement(name = "UDF23")
    protected ItemUDFSetting udf23;
    @XmlElement(name = "UDF24")
    protected ItemUDFSetting udf24;

    /**
     * Gets the value of the udf1 property.
     * 
     * @return
     *     possible object is
     *     {@link ItemUDFSetting }
     *     
     */
    public ItemUDFSetting getUDF1() {
        return udf1;
    }

    /**
     * Sets the value of the udf1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemUDFSetting }
     *     
     */
    public void setUDF1(ItemUDFSetting value) {
        this.udf1 = value;
    }

    /**
     * Gets the value of the udf2 property.
     * 
     * @return
     *     possible object is
     *     {@link ItemUDFSetting }
     *     
     */
    public ItemUDFSetting getUDF2() {
        return udf2;
    }

    /**
     * Sets the value of the udf2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemUDFSetting }
     *     
     */
    public void setUDF2(ItemUDFSetting value) {
        this.udf2 = value;
    }

    /**
     * Gets the value of the udf3 property.
     * 
     * @return
     *     possible object is
     *     {@link ItemUDFSetting }
     *     
     */
    public ItemUDFSetting getUDF3() {
        return udf3;
    }

    /**
     * Sets the value of the udf3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemUDFSetting }
     *     
     */
    public void setUDF3(ItemUDFSetting value) {
        this.udf3 = value;
    }

    /**
     * Gets the value of the udf4 property.
     * 
     * @return
     *     possible object is
     *     {@link ItemUDFSetting }
     *     
     */
    public ItemUDFSetting getUDF4() {
        return udf4;
    }

    /**
     * Sets the value of the udf4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemUDFSetting }
     *     
     */
    public void setUDF4(ItemUDFSetting value) {
        this.udf4 = value;
    }

    /**
     * Gets the value of the udf5 property.
     * 
     * @return
     *     possible object is
     *     {@link ItemUDFSetting }
     *     
     */
    public ItemUDFSetting getUDF5() {
        return udf5;
    }

    /**
     * Sets the value of the udf5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemUDFSetting }
     *     
     */
    public void setUDF5(ItemUDFSetting value) {
        this.udf5 = value;
    }

    /**
     * Gets the value of the udf6 property.
     * 
     * @return
     *     possible object is
     *     {@link ItemUDFSetting }
     *     
     */
    public ItemUDFSetting getUDF6() {
        return udf6;
    }

    /**
     * Sets the value of the udf6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemUDFSetting }
     *     
     */
    public void setUDF6(ItemUDFSetting value) {
        this.udf6 = value;
    }

    /**
     * Gets the value of the udf7 property.
     * 
     * @return
     *     possible object is
     *     {@link ItemUDFSetting }
     *     
     */
    public ItemUDFSetting getUDF7() {
        return udf7;
    }

    /**
     * Sets the value of the udf7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemUDFSetting }
     *     
     */
    public void setUDF7(ItemUDFSetting value) {
        this.udf7 = value;
    }

    /**
     * Gets the value of the udf8 property.
     * 
     * @return
     *     possible object is
     *     {@link ItemUDFSetting }
     *     
     */
    public ItemUDFSetting getUDF8() {
        return udf8;
    }

    /**
     * Sets the value of the udf8 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemUDFSetting }
     *     
     */
    public void setUDF8(ItemUDFSetting value) {
        this.udf8 = value;
    }

    /**
     * Gets the value of the udf9 property.
     * 
     * @return
     *     possible object is
     *     {@link ItemUDFSetting }
     *     
     */
    public ItemUDFSetting getUDF9() {
        return udf9;
    }

    /**
     * Sets the value of the udf9 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemUDFSetting }
     *     
     */
    public void setUDF9(ItemUDFSetting value) {
        this.udf9 = value;
    }

    /**
     * Gets the value of the udf10 property.
     * 
     * @return
     *     possible object is
     *     {@link ItemUDFSetting }
     *     
     */
    public ItemUDFSetting getUDF10() {
        return udf10;
    }

    /**
     * Sets the value of the udf10 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemUDFSetting }
     *     
     */
    public void setUDF10(ItemUDFSetting value) {
        this.udf10 = value;
    }

    /**
     * Gets the value of the udf11 property.
     * 
     * @return
     *     possible object is
     *     {@link ItemUDFSetting }
     *     
     */
    public ItemUDFSetting getUDF11() {
        return udf11;
    }

    /**
     * Sets the value of the udf11 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemUDFSetting }
     *     
     */
    public void setUDF11(ItemUDFSetting value) {
        this.udf11 = value;
    }

    /**
     * Gets the value of the udf12 property.
     * 
     * @return
     *     possible object is
     *     {@link ItemUDFSetting }
     *     
     */
    public ItemUDFSetting getUDF12() {
        return udf12;
    }

    /**
     * Sets the value of the udf12 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemUDFSetting }
     *     
     */
    public void setUDF12(ItemUDFSetting value) {
        this.udf12 = value;
    }

    /**
     * Gets the value of the udf13 property.
     * 
     * @return
     *     possible object is
     *     {@link ItemUDFSetting }
     *     
     */
    public ItemUDFSetting getUDF13() {
        return udf13;
    }

    /**
     * Sets the value of the udf13 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemUDFSetting }
     *     
     */
    public void setUDF13(ItemUDFSetting value) {
        this.udf13 = value;
    }

    /**
     * Gets the value of the udf14 property.
     * 
     * @return
     *     possible object is
     *     {@link ItemUDFSetting }
     *     
     */
    public ItemUDFSetting getUDF14() {
        return udf14;
    }

    /**
     * Sets the value of the udf14 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemUDFSetting }
     *     
     */
    public void setUDF14(ItemUDFSetting value) {
        this.udf14 = value;
    }

    /**
     * Gets the value of the udf15 property.
     * 
     * @return
     *     possible object is
     *     {@link ItemUDFSetting }
     *     
     */
    public ItemUDFSetting getUDF15() {
        return udf15;
    }

    /**
     * Sets the value of the udf15 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemUDFSetting }
     *     
     */
    public void setUDF15(ItemUDFSetting value) {
        this.udf15 = value;
    }

    /**
     * Gets the value of the udf16 property.
     * 
     * @return
     *     possible object is
     *     {@link ItemUDFSetting }
     *     
     */
    public ItemUDFSetting getUDF16() {
        return udf16;
    }

    /**
     * Sets the value of the udf16 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemUDFSetting }
     *     
     */
    public void setUDF16(ItemUDFSetting value) {
        this.udf16 = value;
    }

    /**
     * Gets the value of the udf17 property.
     * 
     * @return
     *     possible object is
     *     {@link ItemUDFSetting }
     *     
     */
    public ItemUDFSetting getUDF17() {
        return udf17;
    }

    /**
     * Sets the value of the udf17 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemUDFSetting }
     *     
     */
    public void setUDF17(ItemUDFSetting value) {
        this.udf17 = value;
    }

    /**
     * Gets the value of the udf18 property.
     * 
     * @return
     *     possible object is
     *     {@link ItemUDFSetting }
     *     
     */
    public ItemUDFSetting getUDF18() {
        return udf18;
    }

    /**
     * Sets the value of the udf18 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemUDFSetting }
     *     
     */
    public void setUDF18(ItemUDFSetting value) {
        this.udf18 = value;
    }

    /**
     * Gets the value of the udf19 property.
     * 
     * @return
     *     possible object is
     *     {@link ItemUDFSetting }
     *     
     */
    public ItemUDFSetting getUDF19() {
        return udf19;
    }

    /**
     * Sets the value of the udf19 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemUDFSetting }
     *     
     */
    public void setUDF19(ItemUDFSetting value) {
        this.udf19 = value;
    }

    /**
     * Gets the value of the udf20 property.
     * 
     * @return
     *     possible object is
     *     {@link ItemUDFSetting }
     *     
     */
    public ItemUDFSetting getUDF20() {
        return udf20;
    }

    /**
     * Sets the value of the udf20 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemUDFSetting }
     *     
     */
    public void setUDF20(ItemUDFSetting value) {
        this.udf20 = value;
    }

    /**
     * Gets the value of the udf21 property.
     * 
     * @return
     *     possible object is
     *     {@link ItemUDFSetting }
     *     
     */
    public ItemUDFSetting getUDF21() {
        return udf21;
    }

    /**
     * Sets the value of the udf21 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemUDFSetting }
     *     
     */
    public void setUDF21(ItemUDFSetting value) {
        this.udf21 = value;
    }

    /**
     * Gets the value of the udf22 property.
     * 
     * @return
     *     possible object is
     *     {@link ItemUDFSetting }
     *     
     */
    public ItemUDFSetting getUDF22() {
        return udf22;
    }

    /**
     * Sets the value of the udf22 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemUDFSetting }
     *     
     */
    public void setUDF22(ItemUDFSetting value) {
        this.udf22 = value;
    }

    /**
     * Gets the value of the udf23 property.
     * 
     * @return
     *     possible object is
     *     {@link ItemUDFSetting }
     *     
     */
    public ItemUDFSetting getUDF23() {
        return udf23;
    }

    /**
     * Sets the value of the udf23 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemUDFSetting }
     *     
     */
    public void setUDF23(ItemUDFSetting value) {
        this.udf23 = value;
    }

    /**
     * Gets the value of the udf24 property.
     * 
     * @return
     *     possible object is
     *     {@link ItemUDFSetting }
     *     
     */
    public ItemUDFSetting getUDF24() {
        return udf24;
    }

    /**
     * Sets the value of the udf24 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemUDFSetting }
     *     
     */
    public void setUDF24(ItemUDFSetting value) {
        this.udf24 = value;
    }

}
